### ISSUE TITLE
Create Slideshow from design

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#101]
From the designs build a carousel see #97 

Please see the home page carousel, discuss with @HedgehogHolly how the carousel should behave on different screen sizes

Acceptance Criteria:
- [x] The Images and content are displayed in a carousel
- [x] The carousel works on mobile and desktop
- [x] On small screen the 2 side images disappear and larger buttons take their place
- [x] There are tests for the component

**Comment by HedgehogHolly** [comment]
@RpprRoger we could probably get rid of this since we are starting from scratch theres nothing to fix?
