### ISSUE TITLE
Preserving blogs.

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#104]
Consider the need to preserve the blogs, how to preserve existing ones and maintain links+redirects.

The need: have the old blog content available at the same URLs as before

We could:
- take the ghost dump and replicate the files in the gatsby repo.
  - Create a markdown file per post
- Download images from server
- Render the markdown using components we have already built for the site
  - https://www.npmjs.com/package/markdown-to-jsx#optionsoverrides---override-any-html-tags-representation
- Make sure the slugs match the path off the root of the site so cached paths work still
- extract meta data from ghost blog page so search results and linking works correctly.

Acceptance Criteria:
- [x] The blogs are stored as markdown in the repo
- [x] A script exists for converting a ghost dump into gatsby blog posts
- [x] Images are resolved correctly
- [x] We have redirects configured for blogs so that existing urls work

**Comment by RpprRoger** [comment]
Initial thinking suggests we could simply leave the old site up, without the navigation. And simply redirect to `blogs.neontribe.co.uk/same-blog-url`

**Comment by RpprRoger** [comment]
We could leave the navigation intact and simply create some redirects to the new urls of the site.

**Comment by RpprRoger** [comment]
It would be best to turn off legacy hosting, how can we achieve that and preserve the blogs? Scraping the blogs means that whilst the new backend is behind worked on new blogs cannot be easily added

**Comment by Kurgol** [comment]
We should not be requiring the old hosting to still be available when we migrate to the new site as that is not viable. 

We need to move the content somewhere else if you are going to be framing it on the new site.

**Comment by RpprRoger** [comment]
Thanks @HedgehogHolly ! 
![Desktop HD Copy 7](https://user-images.githubusercontent.com/1443409/59854311-9957df00-936a-11e9-9532-3a5a2ea008fd.jpg)

**Comment by Kurgol** [comment]
Wow!
