### ISSUE TITLE
Find a typeface

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#111]
In the new designs I've used a typeface that isn't free and I need to find a suitable replacement.

**Comment by katjam** [comment]
Is the cost significant? Might be worth it.

**Comment by HedgehogHolly** [comment]
The one I've used is called Avenir, Im not really sure how much counts as a significant cost or how it works with the rights to use it on the web, I think its based on page views?

https://www.myfonts.com/fonts/linotype/avenir?tab=licensing
https://www.myfonts.com/fonts/linotype/avenir?tab=familyPackages

**Comment by katjam** [comment]
Ugh that's annoying. I mean 250,000 page views is a lot but still something we'd have to wonder about. I was thinking if the license was less than £100 as a one off for web use then OK - but we'd also presumably want a desktop license so you can use it in print and pdf stuff?

I totally agree that paying for high quality is no bad thing. Someone put their time and expertise into that.

Let's see if anyone else has opinions? And/ or if we can get a figure from @marxian @harryharrold @neil-dabson @tobybatch as to how much might be an acceptable amount to spend.

**Comment by HedgehogHolly** [comment]
Yes it would definitely be good to discuss. Ill add it to the agenda for Tuesday as well.

**Comment by HedgehogHolly** [comment]
### Avenir (Paid)
![ourwork-white](https://user-images.githubusercontent.com/41140803/59682011-31b85d00-91cd-11e9-93b8-b7d3570a87b6.png)

### Reneer* (Free)
![ourwork-white copy 3](https://user-images.githubusercontent.com/41140803/59682009-31b85d00-91cd-11e9-817f-b13f25e30436.png)

**Comment by katjam** [comment]
The kerning isn't so good on that free one, but oh well. Beats having to track page views.

**Comment by HedgehogHolly** [comment]
@katjam you think its too wide? isn't that something that can be changed with CSS?

**Comment by katjam** [comment]
It's only at a glance but it looks uneven to me (like there is no kerning). The space needs to vary between character combinations. I might be imagining it but the top one looks more fluid to me.
