### ISSUE TITLE
Create a Favicon

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#113]
Create a Favicon

## Plan
- [ ] Propose a FINAL vote on Nick's proposal vs winners from Holly's votes
- [ ] Make it
- [ ] Use it

## Acceptance Criteria
- [ ] The favicon is changed to the newly considered one

**Comment by HedgehogHolly** [comment]
Im not sure how the Black will look on people (like myself) who use darker skinned browsers. So i've done a purple one as well, not sure how visible the logo will be against the purple on a small scale though.

![favicon](https://user-images.githubusercontent.com/41140803/59519579-10e7c300-8ec0-11e9-804b-132310a31b2e.png)
![BlackLogo](https://user-images.githubusercontent.com/41140803/59519580-10e7c300-8ec0-11e9-9db5-7e7d73ea9b0d.png)

**Comment by katjam** [comment]
I'd like us to try again.

**Comment by katjam** [comment]
Our first attempt - we decided when reduced in size, it became unrecognisable. We've had a conversation in slack.

![Screenshot_20191104_193533](https://user-images.githubusercontent.com/861172/68151558-d5ff2e00-ff39-11e9-8a04-5f2b8568a6f1.png)
![Screenshot_20191104_193612](https://user-images.githubusercontent.com/861172/68151594-ed3e1b80-ff39-11e9-9c83-053a5ab599b1.png)
![Screenshot_20191104_193654](https://user-images.githubusercontent.com/861172/68151654-0646cc80-ff3a-11e9-8d85-2ff7230fece0.png)
![Screenshot_20191104_193727](https://user-images.githubusercontent.com/861172/68151717-237b9b00-ff3a-11e9-9a3d-8efd9c1aad08.png)
![Screenshot_20191104_193843](https://user-images.githubusercontent.com/861172/68151782-45751d80-ff3a-11e9-87a7-918488e40269.png)

**Comment by HedgehogHolly** [comment]
These are some examples. So originally I tried to steer away from the black version because on the dark themed browsers it was impossible to see the logo. Github has the same issue though so maybe we don't need to worry?

<img width="186" alt="example3" src="https://user-images.githubusercontent.com/41140803/68287824-4366a800-007b-11ea-8214-295edc5dea98.png">
<img width="184" alt="example4" src="https://user-images.githubusercontent.com/41140803/68287825-4366a800-007b-11ea-94df-9bc748cc0bb0.png">
<img width="186" alt="example1" src="https://user-images.githubusercontent.com/41140803/68287826-43ff3e80-007b-11ea-8103-fb67db532963.png">
<img width="184" alt="example2" src="https://user-images.githubusercontent.com/41140803/68287828-43ff3e80-007b-11ea-89be-3b2d6258003a.png">

@katjam?

**Comment by katjam** [comment]
@HedgehogHolly can you try it without the words - to give the image more space?
I like the black hexagon with white logo which might also work on the dark theme - since it won't matter if we see the hexagon.

**Comment by HedgehogHolly** [comment]
I think it looks more odd without the text, it looks less recognisable as the logo.

<img width="115" alt="neontribelogo" src="https://user-images.githubusercontent.com/41140803/69228695-ec34fd00-0b7b-11ea-8dee-24c221c37ebb.png">

**Comment by katjam** [comment]
And if you get rid of the text and the hexagon?

**Comment by HedgehogHolly** [comment]
<img width="176" alt="circle" src="https://user-images.githubusercontent.com/41140803/69328257-d5a7a800-0c46-11ea-985b-e7e73911ec9a.png">

**Comment by katjam** [comment]
Yeah - I agree - the bison thing would need a more square ratio to work without the text.

I vote - for sake of making a decision - use the plain old logo without hex but including text so it is square ratio.

Or copy skype and turn it on a diagonal. ;)

**Comment by katjam** [comment]
See if you can get opinions from a couple of other people. At least having the logo will be an improvement on the unrelated hex.

**Comment by HedgehogHolly** [comment]
I'll create a poll on slack so more people can vote on which they prefer. Then I can post the results here.

**Comment by katjam** [comment]
@Nikomus @falconx At this point, I guess we just need a decision. 

I think either of you would be the best candidate for that job. Holly put her visual assets in a Nextcloud dir - which hopefully includes these.

**Comment by Nikomus** [comment]
Removing from the project for now, while we await design changes.

**Comment by Nikomus** [comment]
There is a favicon!
