### ISSUE TITLE
Create more components from design

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#117]
Create components from #97

Acceptance Criteria:
- Components exist:
  - [ ] Employee component
  - [ ] Short work description
  - [ ] long work description
  - [x] Squiggle component
- [ ] Tests exist for new components

**Comment by HedgehogHolly** [comment]
Long Work Example:
![ourwork-white-example](https://user-images.githubusercontent.com/41140803/59851817-724ade80-9365-11e9-86ff-5dd089831f47.png)
