### ISSUE TITLE
Implement new typeface choice

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#122]
We are going with Reneer as it is a nice alternative to Avenir.

https://freebies.fluxes.com/renner-free-typeface/

In this example: 

Main headings are Bold, 40px
Sub headings are Bold, 25px
Paragraphs are Book, 25px

![ourwork-white copy 3](https://user-images.githubusercontent.com/41140803/59683169-88bf3180-91cf-11e9-8313-8ea1289e9c5f.png)

**Comment by RpprRoger** [comment]
I think this translates nicely to the Text component, the `heavy` prop should be set to Bold and everything else set to Book. https://github.com/neontribe/www/blob/master/src/components/Text.js#L37
