### ISSUE TITLE
Final meeting before release 25th June

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#129]
https://meet.google.com/pbx-tztm-egm

**Agenda**
- [x] Sort out testing for Karl (Wednesday 26th June 10am)
- [x] Blog chat from @RpprRoger 
- [x] Have kimai codes been updated?
- [x] Current situation with copy ([look at copy check-list](https://github.com/neontribe/www/issues/112#issuecomment-503591158))
- [x] Whats happening with the privacy policy page?
- [x] Any outstanding PRs?
- [x] Review images for the projects (#130) 
- [x] Outline a plan for the next 3 days / release
- [x] Do we want to set up a social media / twitter post about new website launch

**Notes from the meeting**

- Speak with Karl to book additional testing on Friday and general chat about testing
- The blog will be hidden from the menu but still accessible through links, google and /blogs
- Adding a new blog will currently have to been done through a dev
- Haven is the only project copy that needs to be signed off (@roseb04 speaking to Keshia)
- The three stories still needs to be written (@harryharrold)
- Join the tribe form will be done with Google Forms (@harryharrold and @RpprRoger) 
- The privacy policy has been written
- Booking pathway is the chosen screen for allegiant project image (@HedgehogHolly to mock up)
- Our next steps:  Build the pages from components entering in current copy, chase people's bios, create the survey form, start testing the site
- Finish the website Friday for release on **Monday 1st of July**

**Comment by roseb04** [comment]
Can we also talk about this issue? https://github.com/neontribe/www/issues/92 - about how people contact us if they want to apply for jobs at neontribe

**Comment by roseb04** [comment]
Aiming to be ready by Friday

**Comment by roseb04** [comment]
Planning to drive people to our website via tweets about job vacancies, new funds being available. We would like to write a blog post about the process of updating our website.

**Comment by HedgehogHolly** [comment]
Attendace:  @harryharrold @HedgehogHolly @roseb04 @RpprRoger @katquatermass @amandaneontribe @andybarnes
