### ISSUE TITLE
Create Mood Boards

### ISSUE THREAD

**Issue by katjam** [neontribe/www#13]
**What needs doing?**
Here are two mood boards I made to help convey some ideas Steph, Matt and I discussed initially.

The colour mood board is purely inspiration to pull the colours from. The theme being cybperpunk 80s neon, which we thought is a nicer way to connect to the 'neon' part of Neontribe than the posted note colours.

The design mood board is more of an example of how we might use those colours. Adding splashes of colour throughout the page with geometric shapes to fit in with the Hexagon theme we've gone with.

We obviously will need to keep accessibility in mind if we use the colours in the background or as text colour

**Plan**
- [x] A colour mood board
- [x] A design mood board

**Comment by katjam** [comment]
Design:
![image](https://user-images.githubusercontent.com/861172/49601925-1697a580-f97f-11e8-9d23-30fbe8e7f0ed.png)

**Comment by katjam** [comment]
Colour:
![moodboard1](https://user-images.githubusercontent.com/861172/49602085-8017b400-f97f-11e8-9f0a-db237cad47fc.jpg)

**Comment by katjam** [comment]
@HedgehogHolly Are you expecting to work on this anymore - or consider it completed? I have added to the https://github.com/neontribe/www/projects/3 - but not sure if it should remain open.

If you intend to do further mood boards - please keep open and add to https://github.com/neontribe/www/projects/2

If you are finished, please close.

**Comment by HedgehogHolly** [comment]
@katjam I'm no longer working on it but I'm not sure if anyone wanted to discuss it? we got a few comments from people but I'm not sure what the general consensus is. If people don't like it then I'll need to look at making another set of mood boards.

**Comment by katjam** [comment]
@HedgehogHolly Thanks. I'll close it then - and put a reminder in the slack for people to comment.

**Comment by katjam** [comment]
Loving the colours. Design seems a bit on the corporate side to me... but happy to go with your instincts. My design sense is terrible.

**Comment by jermyk** [comment]
@HedgehogHolly 
Love the neon, but the design looks too busy (IMHO)

I could look at the "neon" board as a whole but felt my eyes were all over the place when looking at the "design" board
Hope that makes sense?

**Comment by karalan** [comment]
I agree with @jermyk and @marxian - love the palette but find the design board a bit too disparate and lacking in the personality conveyed by the colour palette.

**Comment by katjam** [comment]
@HedgehogHolly Looks like enough people would love to see you explore design a bit more. Support all round for the colours.

**Comment by HedgehogHolly** [comment]
Sounds good, I honestly thought that neontribers would find the cyber-punk aesthetic too over the top so I didn't explore into more full on designs and went for more subtle uses of it but I can definitely do more design research 😃

**Comment by katjam** [comment]
Closing - further mood work will be dine later.
