### ISSUE TITLE
Images for projects copy

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#130]
We have copy for the selected projects, we need images 

- [x] Mind of my own
- [x] Alexandra Rose
- [x] seAp
- [x] Haven 
- [x] Allegiant

![Screenshot 2019-06-21 at 14 02 07](https://user-images.githubusercontent.com/41140803/59924236-35e2b580-942d-11e9-8aeb-2d366b1032fe.png)
![Screenshot 2019-06-21 at 16 48 16](https://user-images.githubusercontent.com/41140803/59934859-6aae3700-9444-11e9-8fd4-76021ed4cc61.png)
![Screenshot 2019-06-21 at 14 00 49](https://user-images.githubusercontent.com/41140803/59924197-1481c980-942d-11e9-8f29-00d7498d3285.png)
![Screenshot 2019-06-21 at 14 02 20](https://user-images.githubusercontent.com/41140803/59924244-3bd89680-942d-11e9-87bd-24dc32885341.png)
![Screenshot 2019-06-25 at 17 39 25](https://user-images.githubusercontent.com/41140803/60116571-356d5600-9770-11e9-84d8-5ffc0f8c945b.png)

**Comment by HedgehogHolly** [comment]
Haven:

![Haven](https://user-images.githubusercontent.com/41140803/59915958-d200c280-9415-11e9-924d-0596413b69e3.jpg)

**Comment by HedgehogHolly** [comment]
Mind of my own: 

![Momo](https://user-images.githubusercontent.com/41140803/59916211-74b94100-9416-11e9-8404-fe27aa6a3128.jpg)

**Comment by HedgehogHolly** [comment]
seAp:

![seAp](https://user-images.githubusercontent.com/41140803/59923514-822cf600-942b-11e9-8298-ec116b75e908.jpg)

**Comment by HedgehogHolly** [comment]
Alexandra Rose: 

![App Pic veg-8256 1  copy 3](https://user-images.githubusercontent.com/41140803/59923699-f8c9f380-942b-11e9-8628-a512c232ac8e.jpg)

**Comment by katjam** [comment]
The mind of my own one needs an update that's with the old MOMO logo.

**Comment by HedgehogHolly** [comment]
@katjam ah yeah no worries, I'll update it

**Comment by roseb04** [comment]
Booking pathway for Allegiant on laptop

**Comment by HedgehogHolly** [comment]
![Allegiant](https://user-images.githubusercontent.com/41140803/60116448-ec1d0680-976f-11e9-94d1-d4e01a6f6898.jpg)
