### ISSUE TITLE
Testing Notes

### ISSUE THREAD

**Issue by jermyk** [neontribe/www#148]
Notes from testing https://neontribe.now.sh/ first sweep

**Comment by jermyk** [comment]
- [x] Blue boxes appearing around images and back and forth arrows on carousel
 - [x] Error from https://neontribe.now.sh/google-apps-for-business-disabling-confidential-mode/
![Screenshot_062819_124740_PM](https://user-images.githubusercontent.com/4446325/60340234-e9562780-99a2-11e9-898f-afa000cf32e2.jpg)

 - [x]
 - [x]

**Comment by jermyk** [comment]
@rob @HedgehogHolly 

Notes thus far above..

**Comment by RpprRoger** [comment]
Thanks Karl! I'll card the last thing on your test which we need to consider
