### ISSUE TITLE
Create wordpress.com account

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#16]
**What needs doing?**
Create wordpress.com account and investigate integration with gatsby-source-wordpress
The wordpress.com site should be hidden from the internet

**Plan**
- [x] create a WP email alias
- [x] add pertinent neontribers to the alias
- [x] Setup the wordpress account
- [x] Install a basic wordpress thing on it.
- [x] Hide the WP site from Google
- [x] Investigate GraphQL api plugins for WP
- [ ] Investigate GraphQL clients for Gatsby (it's probably Apollo)
- [ ] Have a quick chat with the Design folks to see what ~~security liabilities~~ plugins / capabilities they may need.

**Acceptance Criteria**
- [x] We have a common wordpress account NOT under pre-existing shared account, under something else
- [x] There is a basic wordpress install available
- [x] This is not searchable by Gooogle (to avoid frowns and sadness from google's algorithms)
- [x] It has some kind of API, probably GraphQL, that can be consumed by a client.
- [ ] The configuration is published on owncloud
- [ ] We have a list of things the Design folk want to do, and a ensemble of ~~security liabilities~~ plugins to make that happen.

We will need to create a new Wordpress App at some point and get hold of the wpcom_app_clientSecret and wpcom_app_clientId for the gatsby-source-wordpress config.

Stretch goal: how do we import the old ghost content? The attached json only has references to images. The images are on the filesystem and we can add them too.

**Comment by marxian** [comment]
I think there's maybe a misapprehension in this issue.

The canonical way to connect gatsby to wordpress is via gatsby-source-wordpress https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-wordpress

**Comment by katjam** [comment]
Closing. We've done the rigging and initial set up.

**Comment by katjam** [comment]
The isitial set up has been done We need to make decisions on the PR (maybe strip it back so it's just the initial connection) - and worry about pulling content through in the next stage?

**Comment by katjam** [comment]
Closing - content stuff is done in #35 

The wp account has been set up - details in owncloud? I think...
