### ISSUE TITLE
Meta tags for the main pages for the site

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#165]
```
Rupert [5:32 PM]
And we could use a meta description...

Rupert [5:34 PM]
@harry can you draft a meta for the three main pages?
```

**Comment by harryharrold** [comment]
Up to 160 characters.

Main: "Neontribe is a digital agency. We learn from users, build something small, then measure how that’s helped. We hit deadlines, and make best use of your budget.”

Tribe: “Neontribe is a digital agency. Why neon? It’s the light of technology. Why tribe? Individuals collaborating, hand-making useful tools that do a job of work. 

Works: “Neontribe is a digital agency. We research for context. We design for use. We code to completion. We test to exhaustion. Then we engineer enhancement.”

**Comment by harryharrold** [comment]
@katquatermass ...I think my sugar-rush may not be helping. Review plzthx.

**Comment by katjam** [comment]
@harryharrold You definitely have a talent (or hard earned skill) for marketing copy! :clap:

**Comment by katquatermass** [comment]
Will message you @harryharrold . They're slick - But I don't know enough about meta tags to know how/where this stuff displays, in what way, and what crawls it for what to know how to comment on it!
