### ISSUE TITLE
"xXx years later" in Katja's story

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#166]

**Comment by katjam** [comment]
It's a difficult sentence to complete - but the way it is worded now - would be `current year - 2008` I think.

Would it be better if 'xXx years later I was leading code projects to completion' with the date I started leading (6 years later?)'

Or 'Now I lead and code projects to completion'

Then I met Neontribe through a colleague at the BBC, and started two days a week with them. xXx years later I lead and code projects to completion.

@harryharrold thoughts?

**Comment by harryharrold** [comment]
"Would it be better if 'xXx years later I was leading code projects to completion' with the date I started leading (6 years later?)'"

I like this - sorry,  that sentence could have been better...

**Comment by katjam** [comment]
@harryharrold Yeah - sad to lose the great phrase 'code projects to completion' though I also think the 6 years has more meaning than the now version.

**Comment by katjam** [comment]
@harryharrold I'm not sure about the time though - it may have been only 4-5 years. What do you remember as first project I lead? Apps for good disaster was likely my fault... which was 8 years ago. But officially might have been day in life or bananalink or the sarah projects - time for me? Always in the early days was me and Heydon or me and Matt so I had a design lead with me. Probably best to just put an arbitrary year that is a good target for people to hit in terms of starting out to becoming a lead.

**Comment by HedgehogHolly** [comment]
Could either @katjam or @harryharrold update the copy on the [doc ](https://docs.google.com/document/d/1Vpi33yeieEFS-Y3SwLOzof4ONe_qY80aIXtOhVAkbzA/edit?usp=sharing) and let me know when you're happy with it otherwise we can just remove that sentence for now?

**Comment by katjam** [comment]
@HedgehogHolly I think @harryharrold must have updated copy doc. Looks good to me there now.

**Comment by katjam** [comment]
```
I was coding as a kid, and stopped to go into film but later missed programming and started an OU course. However, I didn't have the confidence to get into the industry without recent experience. Then I met Neontribe through a colleague at the BBC, and started two days a week with them. Soon, I was coding projects to completion. 5 years later, I was leading them. Importantly, I've never felt any guilt about fitting my hours around my children. It's not *just* the company policy, it’s that nobody has ever judged the hours I work. It takes the stress out of delivering to the deadlines our projects need us to hit.
```

**Comment by harryharrold** [comment]
@katjam approves....
