### ISSUE TITLE
Tribe carousel arrows become emojis on iOS Safari

### ISSUE THREAD

**Issue by stphnnnn** [neontribe/www#169]
**Describe the bug**
![image_from_ios](https://user-images.githubusercontent.com/53346/60422834-c2873380-9be4-11e9-9a65-eef6ac06bf0c.png)

**Device**
 - OS: iOS
 - Browser: Safari

**Additional context**
Using SVGs for these arrows will probably fix this issue

**Comment by HedgehogHolly** [comment]
Should be fixed by issue #181
