### ISSUE TITLE
List of design fixes

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#184]
**What needs doing?**
I thought it be good to write a list of design fixes that need to be done either now if they are easy fixes or in the next sprint

**Issues**
- [ ] Small white corner visible on the problem summary card 
![Screenshot 2019-07-01 at 13 32 06](https://user-images.githubusercontent.com/41140803/60436800-c1fe9500-9c04-11e9-8f25-a90b8f97b01d.png)

- [ ] Padding on the nav links 
![Screenshot 2019-07-01 at 13 59 49](https://user-images.githubusercontent.com/41140803/60438452-9c738a80-9c08-11e9-9eb9-82d1abdd3526.png)

- [ ] Squiggle sometimes shows extra little shape
![Screenshot from 2019-07-01 14-43-33](https://user-images.githubusercontent.com/53346/60441388-c62fb000-9c0e-11e9-9738-d2d19e12a0c1.png)

- [ ] Fix orphan by adding more padding?
![Screenshot 2019-07-01 at 15 53 14](https://user-images.githubusercontent.com/41140803/60446049-6a6a2480-9c18-11e9-8104-5419cee47f72.png)

- [ ] Maybe having people's last name as well as first on the stories would look visually better? since we do have surnames on the tribe page
![Screenshot 2019-07-01 at 16 08 00](https://user-images.githubusercontent.com/41140803/60447049-8373d500-9c1a-11e9-8d90-5e3bd11037b1.png)

**Comment by falconx** [comment]
> Fix orphan by adding more padding?

with CSS we have control over [orphans](https://developer.mozilla.org/en-US/docs/Web/CSS/orphans) and [widows](https://developer.mozilla.org/en-US/docs/Web/CSS/widows) but they're not quite the same thing that we're talking about here.

you could add `padding` but then if the copy changes, we'd potentially have the same issue again.

other solutions are;
* inject a `&nbsp;` between the last two words
* wrap the last two words with `<span style="white-space: nowrap">`

**Comment by HedgehogHolly** [comment]
Yeah that's weird, I tried both Windows and Mac, Chrome and Safari.  I can't see the white corner on the summary card anymore. Or the extra shapes.  I think I remember fixing the padding with you a while back. 

So if you've fixed the padding/orphan issue I think we are all good.  The others must have fixed themselves some how.

**Comment by katjam** [comment]
@katquatermass Make a new issue referencing the orphan part of this for your copy change.
