### ISSUE TITLE
Various typos and grammar

### ISSUE THREAD

**Issue by stphnnnn** [neontribe/www#185]
Below is a list of some typos myself and @HedgehogHolly have found 

Holly: I used the Grammarly website to pick up a lot of these

**Home**
- [x] practise -> practice
- [x] sous chef -> sous-chef

**What we're doing**
- [x] their situations and stories -> their situations and stories.
- [x] confusing,overwhelming -> confusing, overwhelming

**Harry's Bio**
- [x] the latter, and -> the latter and

**Charlie's Bio** 
- [x] ,. -> .
- [x] directing a SME focused IT services company -> directing an SME focused IT services company

**Matt's Bio**
- [x] by the time you read this I probably -> by the time you read this I will probably

**Toby's Bio**
- [x] I'm hold an -> I hold an

**Neil**
- [x] Cyber security -> Cybersecurity
- [x] Fortunately times have moved on ->  Fortunately, times have moved on 
- [x] As some light relief I take scouts -> As some light relief, I take scouts
- [x] my hobby of live action -> my hobby of live-action 
- [x] role play runs smoothly -> role-play runs smoothly

**Katja**
- [x] vim and linux -> Vim and Linux
- [x] community, open source, transparency -> community, open-source, transparency
- [x]  coding as a kid, and ->  coding as a kid and
- [x] at the BBC, and -> at the BBC and

**Karl**
- [x]  my work life balance  ->  my work-life balance 
- [x] child care/school runs etc.-> childcare/school runs etc.
- [x] Outside of the office -> Outside of the office,

**Andy**
- [x] Neontribe also sponsor me studying a degree -> Neontribe also sponsors my degree in Computer Science 

**Kara**
- [x] so worked in -> so I worked in
- [x] self taught SQL and ended -> self-taught SQL and ended 
- [x]  process related; as ->  process-related; as

**Rose**
- [x] During my time in the sector I was -> During my time in the sector, I was

**Kat**
- [x] 15 year career -> 15-year career
- [x] Can frequently be found doing game design -> I can frequently be found doing game design

**Nick**
- [x]  game development company, ->  game development company

**Rob**
- [x] College cancelled the -> The college cancelled the

**Comment by notpluto** [comment]
Hi @HedgehogHolly and @stphnnnn! Is this issue being worked on?  I'm interested in taking it up.

**Comment by marxian** [comment]
Hey @notpluto !

It is super-nice of you to offer to help out. We just wanted to check that you know that this is our company website and not a widely-reusable open-source project. If you're looking to make a difference in the world, or to gain some experience and profile by making contributions to open source software there are definitely projects which deserve your hard work more than we do.

We like to work in the open when we can - which is why this project isn't private - but we honestly never expected folk outside the company to want to get involved.

If your motive is simply to make friends in far-flung places then we reckon fixing up the typos of strangers is a brilliant strategy!

**Comment by notpluto** [comment]
Thank you @marxian! It's really sweet of you to say this :) Yes, I wasn't aware that this project belonged to your company. Being relatively new to the open-source community I was looking for issues with 'Good First Issue' labels and that's how I ended up here.

That said, I would still like to take this up just to get familiar with the entire approach before moving on to other projects.

**Comment by marxian** [comment]
@notpluto If we can help you get comfortable with contributing then at least we'd have been of some use.

If you want any assistance with Pull Requests and such please let us know.

**Comment by notpluto** [comment]
You've been wonderful in allowing me to make my first contribution to the community, @marxian. 

I have made the suggested changes for this issue and submitted a PR. Please review.
