### ISSUE TITLE
Anonymise the analytics we collect to GA

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#190]
We don't care about IPs, we can tell GA to stop collecting them https://support.google.com/analytics/answer/2763052?hl=en 

Is there anything else we can **not** collect?

### Plan:
- [ ] Disable collecting IPs, either in GTM or GA
- [ ] Think about disabling anything else which we don't need to collect to help understand our audience better

**Comment by roseb04** [comment]
The open rights org use something called Matomo, which is open source - https://matomo.org/. Maybe we could use this instead?

**Comment by charlesstrange2** [comment]
@roseb04 we might have to run our own instance of it.

**Comment by RpprRoger** [comment]
I don't think we should switch to a paid for or self hosted tracking solution right now.

**Comment by RpprRoger** [comment]
I have a feeling we would need to opt in to collecting extra personal data. We should check the docs and/or the TOS together tomorrow.

**Comment by charlesstrange2** [comment]
My ethical issue is, even if we lock down GA, and google doesn't share the user data with us until we hit a useful number of pages, is GA *still* fingerprinting users?

Can we have an opt-out (or better, opt-in) to GA tracking for users?

**Comment by roseb04** [comment]
So a quick research finds that there is a browser extension people can install that will disable the GA Javascript, we could link it in our privacy policy - https://support.google.com/analytics/answer/181881?hl=en. 
The slight ethical problem then is that the onus is on the individual rather than us to do anything.

**Comment by charlesstrange2** [comment]
https://webgilde.com/en/analytics-opt-out/
seems to have a cookie based opt out, where we don't activate analytitcs if they don't want it. 

Can we not ask the user if they want to help us by letting us track their interaction? 

We could
- land them somewhere that's GA free/disabled, if they haven't made a privacy choice yet;
- point them at the chrome extension (anmaybe EFF privacy badger, Ghostery, etc. 
- ask them nicely if they want to help us?

**Comment by roseb04** [comment]
Once we develop the opt-in for GA when we re-add it to the site, I would like to think about what questions we want it to help us answer, look into the tools that GA have to help us answer some of those (I'm thinking about using the events tool and dashboard reporting).

**Comment by roseb04** [comment]
Closing as part of #207
