### ISSUE TITLE
Email page copy

### ISSUE THREAD

**Issue by jermyk** [neontribe/www#195]
On the page the copy says Join the tribe

* The logo on the page suggests tribe should be spelt "Tribe" as does the button that nav's the user to the email page 
![Screenshot_070119_054643_PM](https://user-images.githubusercontent.com/4446325/60453140-30a11a00-9c28-11e9-8963-a37a8ffebedc.jpg)

* The copy in the page doesn't give an indication as to when we might get back tho the person who has contacted us? (Actually it does but I struggled to see it on the intro page).....

**Comment by jermyk** [comment]
![Screenshot_070119_054233_PM](https://user-images.githubusercontent.com/4446325/60452920-9c36b780-9c27-11e9-866d-1b445d0118e5.jpg)



![Screenshot_070119_053429_PM](https://user-images.githubusercontent.com/4446325/60452873-7e695280-9c27-11e9-8305-ec5bd78f8160.jpg)

**Comment by katjam** [comment]
closing as part of #198
