### ISSUE TITLE
Think about tracking in a more open way

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#202]
Thoughts from @charlesstrange2 

> To be fair my ideal solution that included 3pt would be
> - don't fetch code from Google, keep it on the site
> - pull the latest scripts when we build it. 
> - default it off
> - present some kind of privacy manager if we can't tell they've opted before
> -... That asks them to make a choice to help us with our ux (default no)
> -... That keeps 3pt off if they close it without choosing 
> -... That enables it with an url query string if they say yes
> -... That links to the PrivPolicy
> -... Which tells them where to get privacy tools

**Comment by charlesstrange2** [comment]
If we must track, make sure that the users opt-in. Is it fair that we ship their usage off to google without their informed consent? A site out size can hardly justify metrics like this as an operational business requirement.

**Comment by charlesstrange2** [comment]
Further as a group with aspirations of ethical practice, should we not put that into practice?

**Comment by RpprRoger** [comment]
I can see your point, I believe that it is strikingly different to see how people use our site. The unethical approach is looking at the type of people that do, which we're **not** interested in doing. 

I don't agree that the metrics aren't useful.
Let's have a chat

**Comment by katjam** [comment]
I haven't followed this conversation - but I believe it is easy to turn off the 'demographics' tracking in GA (at least it used to be) since that was a part people had to opt in to.

**Comment by RpprRoger** [comment]
Thanks! Yeah we should make sure that we aren't tracking that more personal data. We've condensed some of these thoughts into the card for the slide over and the card for tracking less data, see #190 and #207
