### ISSUE TITLE
The Tribe - Typos

### ISSUE THREAD

**Issue by jermyk** [neontribe/www#204]
**Charlie**

Charlie has a comma next to a full stop.

mild addiction to certification to bluff his way as an InfoSec **pundit,.** He swims regularly for the secre

**Neil**

I still remember when Norwich didn’t have broadband **(with was this century).** 
Should be "which was this century"

**Comment by Kurgol** [comment]
The deploy of my pull request failed because of package manager failure, and I don't know how to get it to trigger another build?
