### ISSUE TITLE
The casing of profile's "three words" are not consistent

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#214]
**What needs doing?**
Make the cases of the three words on a profile card the same. Most profiles capitalise every word, some only the first letter of a phrase and some a mixture.

**Plan**
- [ ] decide on a standard casing
- [ ] check through copy and apply

**Comment by stphnnnn** [comment]
Title or sentence case makes sense to me, I agree that we should pick 1 for consistency 👍

**Comment by Kurgol** [comment]
given the mix of "three | words | together" and "sentences that roll | onto one | another" are all mixed together, I'm actually leaning towards preferring all lower case?

**Comment by katquatermass** [comment]
From what we know about twitter hashtags and lack of capitalisation being an issue I think we could extrapolate that all lower case is a readability issue in general.  So preference for capitalising first letters of phrases or words, and more than first letter if the phrase is a proper noun or title. (I don't know which of sentence or title case that is, sentence I think)

**Comment by katjam** [comment]
@zii-67 We need Acceptance Criteria on this one.
