### ISSUE TITLE
Browser testing Issues

### ISSUE THREAD

**Issue by jermyk** [neontribe/www#218]
Record Browser testing Issues here

**Comment by jermyk** [comment]
**Edge**

Page loading carnage
![Screenshot_070219_030447_PM](https://user-images.githubusercontent.com/4446325/60519093-bbdae800-9cda-11e9-8c88-6b9d382b25df.jpg)

**Comment by jermyk** [comment]
**Edge**

Pink underline doesn't display for the user as per Chrome
![Screenshot_070219_030741_PM](https://user-images.githubusercontent.com/4446325/60519276-23913300-9cdb-11e9-8883-f4d7d12297e9.jpg)

**Comment by jermyk** [comment]
**Edge**

Pink styling left aligned on  meet the tribe page

![Screenshot_070219_030911_PM](https://user-images.githubusercontent.com/4446325/60519380-59361c00-9cdb-11e9-981d-a9c790fcfa1b.jpg)

**Comment by jermyk** [comment]
**Edge**

Images displaying in rows of two
![Screenshot_070219_030911_PM](https://user-images.githubusercontent.com/4446325/60519443-7539bd80-9cdb-11e9-9d7d-3e33d99b2ec3.jpg)

**Comment by jermyk** [comment]
**Edge**

Image flip varies and sometimes displays text and image together.
![Screenshot_070219_031155_PM](https://user-images.githubusercontent.com/4446325/60519576-baf68600-9cdb-11e9-8fa9-d45bc5e2caeb.jpg)

**Comment by jermyk** [comment]
**Edge**

Spot the difference!
![Screenshot_070219_031329_PM](https://user-images.githubusercontent.com/4446325/60519693-f98c4080-9cdb-11e9-80c1-d252ab9c0857.jpg)

**Comment by jermyk** [comment]
**Edge**

Link to privacy policy doesn't fire

![Screenshot_070219_031814_PM](https://user-images.githubusercontent.com/4446325/60520044-9cdd5580-9cdc-11e9-85b0-2d0b85d9ccaf.jpg)

**Comment by jermyk** [comment]
**Edge**

Carousel sizing (and bottom right hand corner cut away)
![Screenshot_070219_032427_PM](https://user-images.githubusercontent.com/4446325/60520529-7b309e00-9cdd-11e9-97bd-5af78b192327.jpg)

**Comment by jermyk** [comment]
**Edge**
Carousel doesn't scroll, images move into text box
![Screenshot_070219_032707_PM](https://user-images.githubusercontent.com/4446325/60520746-da8eae00-9cdd-11e9-8d23-9587460b696d.jpg)

**Comment by jermyk** [comment]
**Edge**

Images are slow to load
![Screenshot_070219_033336_PM](https://user-images.githubusercontent.com/4446325/60521327-f8104780-9cde-11e9-8f80-62432ba0773d.jpg)

**Comment by jermyk** [comment]
**Firefox**

Image sizing on carousel
![Screenshot_070219_035347_PM](https://user-images.githubusercontent.com/4446325/60522806-943b4e00-9ce1-11e9-9018-4d2d49b0b911.jpg)

**Comment by Kurgol** [comment]
Microsoft Edge 44.18362.1.0
Microsoft EdgeHTML 18.18362 

Some pictures don't revert to b&w when your mouse leaves their pane. 

![image](https://user-images.githubusercontent.com/15245142/60523127-1cb9ee80-9ce2-11e9-9c8a-2c1307d1236e.png)

**Comment by jermyk** [comment]
**Firefox**

Loading reverse images when selected.
![Screenshot_070219_040902_PM](https://user-images.githubusercontent.com/4446325/60524029-b7ff9380-9ce3-11e9-97c8-cd49468ef00c.jpg)


Instant Russian, just click! 
![Screenshot_070219_041031_PM](https://user-images.githubusercontent.com/4446325/60524341-483dd880-9ce4-11e9-9c5c-7579a86e5ce8.jpg)

**Comment by RpprRoger** [comment]
@jermyk Thanks! I've carded these into issues that I think we should fix prelaunch and postlaunch.
I carded: 
- https://github.com/neontribe/www/issues/218#issuecomment-507697826: https://github.com/neontribe/www/issues/228
- Pre launch #229 
- Post launch #230 

I haven't carded the firefox triber card one: https://github.com/neontribe/www/issues/218#issuecomment-507721274 because it's mentioned elsewhere: #226
