### ISSUE TITLE
Firefox: Triber profile flip doesn't show bio.

### ISSUE THREAD

**Issue by ob6160** [neontribe/www#226]
**Describe the bug**
In Firefox: profile image flip simply shows reversed image instead of hiding image and showing bio.

**To Reproduce**
Try to flip a "Triber" tile in Firefox.

**Expected behavior**
Profile image flip displays the bio text when a Triber's tile is clicked.

**Screenshots**
![When flipped the profile bio isn't displayed](https://i.imgur.com/L2YKts0.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 67.0.4

**Comment by RpprRoger** [comment]
This is mentioned here: https://github.com/neontribe/www/issues/218#issuecomment-507721274
