### ISSUE TITLE
'The Tribe' heading on landing page

### ISSUE THREAD

**Issue by alexalala** [neontribe/www#235]
I think 'The Tribe' heading on the landing page with the carousel under, makes it look like we just have 3 members of the tribe. Heading wording could be improved.

**Comment by alexalala** [comment]
![Screen Shot 2019-07-04 at 14 00 36](https://user-images.githubusercontent.com/11891294/60668455-ee641c80-9e63-11e9-97ae-f14d7636cc07.png)

**Comment by marxian** [comment]
II'm a bit unclear why there are only three folk in this carousel? I'm sure I've missed a useful discussion at some point...

**Comment by alexalala** [comment]
Yeah, I think the purpose of this carousel is to tell a small portion of Tribers' journeys into tech & into Neontribe. But I don't think that's explained very well here!

**Comment by RpprRoger** [comment]
> II'm a bit unclear why there are only three folk in this carousel? I'm sure I've missed a useful discussion at some point... Like... why do we slice here?
> 
> https://github.com/neontribe/www/blob/master/src/components/StoryCarousel.js#L60

The Carousel itself only supports 3 items. We would want to improve the carousel so it can support more than 3 items

**Comment by RpprRoger** [comment]
Until we have stories for more than 3 stories and the carousel can support any number of items, shall we make the copy clearer?

**Comment by Kurgol** [comment]
I think changing the copy to "Journey to the Tribe" would probably fit better - but someone wordier than me would probably provide better copy!
