### ISSUE TITLE
Carousel bug in (Alex's) Chrome

### ISSUE THREAD

**Issue by alexalala** [neontribe/www#237]
Carousel hexagons not expanding when clicked on:

![Screen Shot 2019-07-04 at 15 11 56](https://user-images.githubusercontent.com/11891294/60673582-f7f38180-9e6f-11e9-9b39-50f9760df23f.png)

**Comment by jthistle** [comment]
Can't reproduce, Chrome Version 75.0.3770.100 (Official Build) (64-bit), Ubuntu 18.04 LTS, i3wm.

**Comment by alexalala** [comment]
Not occuring on live, will close.
