### ISSUE TITLE
Social Media Links In Bios

### ISSUE THREAD

**Issue by ob6160** [neontribe/www#248]
**Is your feature request related to a problem? Please describe.**
I wanted to link to my Twitter account through my bio but had to resort to using a markdown link in my bio text.

**Describe the solution you'd like**
I think it'd be good to have a dedicated field in the bio markdown for twitter handles and render a little twitter bird (or other relevant social media logo) *somewhere* on the bio card.

Thoughts?

## Plan

- [x] allow links in triber markdown files under 'social', i.e.:

```
    social:
      twitter: '@helloworld'
      github: 'helloworld'
```

- [x] display icons using fontawesome

## Acceptance criteria

- [x] @HedgehogHolly approves the design

- [x] social media links are quick and easy to add for any 'triber', not requiring more than editing the markdown file

- [x] clicking links will take you straight to the profile page

**Comment by stphnnnn** [comment]
sounds good to me :+1:

**Comment by Kurgol** [comment]
Agree. Great idea. can we have ones for twitch as well please =)
