### ISSUE TITLE
Add Legally needed info to MVP

### ISSUE THREAD

**Issue by katjam** [neontribe/www#25]
**What needs doing?**
Agree/ verify a list of legally needed content to include

**Acceptance Criteria**
- [ ] All info in the agreed list is included in the designs as a must have.

**Comment by katjam** [comment]
@Nikomus  suggested:
On business letters, order forms and websites, you must show:

- the company’s registered number
- its registered office address
- where the company is registered (England and Wales, Scotland or Northern Ireland)
- the fact that it’s a limited company (usually by spelling out the company’s full name including ‘Limited’ or ‘Ltd’)
If you want to include directors’ names, you must list all of them.

Was: https://trello.com/c/DmC2AHwm/63-legally-needed-info

**Comment by katjam** [comment]
@harryharrold @katquatermass Not sure if we agreed the checklist items or if we need more research here.

Suggest @neil-dabson might be the person to sign off and close this? And @gingerbreadpup @HedgehogHolly to verify that we include in designs...

**Comment by katquatermass** [comment]
I like "a small section somewhere" for legal info. It is similar to how we
often do privacy statement for clients "a link somewhere".
