### ISSUE TITLE
Screenreaders read out dot operator in title as "times"

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#252]
**What needs doing?**
The dot operator used in the title to separate the page name from Neontribe is read out as "times" by screen readers (NVDA, ChromeVox).

**Plan**
- [ ] Choose a new separator
- [ ] Update gatsby-config.js `titleTemplate`

**Comment by AlinChindea** [comment]
`ChromeVox` doesn't read it on Chrome for Fedora.

**Comment by Nikomus** [comment]
This may only be on Windows, but I can hear it on Win10+NVDA and Win10+ChromeVox.

**Comment by zii-67** [comment]
Does it still read as times?

> This may only be on Windows, but I can hear it on Win10+NVDA and Win10+ChromeVox.

**Comment by zii-67** [comment]
I tried on my own device, it doesn't read out.
