### ISSUE TITLE
Add neon focus borders for 'triber' cards

### ISSUE THREAD

**Issue by jthistle** [neontribe/www#254]
Related to #162. The cards on the 'The tribe' page have buttons that can be focussed to allow the cards to be flipped by keyboard. When one of these buttons is focussed, the entire card (the parent of the button) should display the focus styles implemented by the fix for #162.

## Plan (todo)

**Comment by falconx** [comment]
Accidentally fixed with https://github.com/neontribe/www/pull/321

**Comment by katjam** [comment]
@zii-67 Please verify and then close this issue.

**Comment by katjam** [comment]
Awaiting code review

**Comment by RabidGamer** [comment]
Neon focus border shows.

![image](https://user-images.githubusercontent.com/48025294/77917303-511f0300-7292-11ea-918f-19fc1af9571e.png)
