### ISSUE TITLE
Catch-up meeting 16 July

### ISSUE THREAD

**Issue by katjam** [neontribe/www#257]
**What needs doing?**

**Agenda**
- [ ] Review actions from #129 
- [ ] Discuss any outstanding PRs
- [ ] Discuss / agree process for promoting features and bugs into priority/ scope for action

**Actions**

**Comment by katjam** [comment]
![Screenshot_20190711_132224](https://user-images.githubusercontent.com/861172/61050303-a6eb0c80-a3de-11e9-9379-2404edd37061.png)

**Comment by katjam** [comment]
For client projects the process goes from Identify a potential need, validate that it is a need, discuss potential solutions, test them if warranted, agree a fit for purpose/ nice affordable solution, code the thing.

It would be great if we can use a similar pipeline. Since the work is unlikely to be organised in time boxed sprints, it will be fun to discover a process that allows us to do this work ad hoc. Some of our client project could benefit from this approach too.

Also perfectly possible to have parallel agendas. Consider use of milestones (which contain ordered issues).

**Comment by roseb04** [comment]
closing because no actions
