### ISSUE TITLE
Allow the carousel to include more than 3 people

### ISSUE THREAD

**Issue by rosejbon** [neontribe/www#270]

**Comment by katquatermass** [comment]
Is against original intentions of carousel. This is meant to be 2 or 3 key messages about routes people take to the company - the most unusual ones, or the ones most likely to validate an unusual pathway. The more entries it has, the less it meets that specific tailored user need.

**Comment by katjam** [comment]
@roseb04 @katquatermass Are we happy to close this? Do you remember why it was added? User need?

**Comment by katquatermass** [comment]
Closing as we are not using the carousel anymore
