### ISSUE TITLE
[Blog] View not responsive/needs work on responsiveness

### ISSUE THREAD

**Issue by RabidGamer** [neontribe/www#277]
**Describe the bug**
Go to "www.neontribe.co.uk/blog/contemplating-action" on a smartphone.

See the bug.

**Expected behavior**
The webpage loads without looking like an elephant took a poop on the css.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:Samsung S8
 - OS: Android
 - Browser: Chrome

**Comment by RabidGamer** [comment]
![Screenshot from 2019-08-08 15-42-50](https://user-images.githubusercontent.com/48025294/62712758-5e316e00-b9f3-11e9-96be-f97e238a6f31.png)

**Comment by katjam** [comment]
Closing as mentioned as part of #247
