### ISSUE TITLE
Washup meeting 10 September

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#282]
## Regular meeting

**Plan**
- [x] Review actions from last meeting
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board

### What did we get done?
- The new website exists
- No blog post URL left behind
- A structured means of enquiring for jobs
- Blog posts are stored and indexed by Google
- Gives a more accurate impression of us as a company
- Got rid of process page and just have a projects page

### What did we not get done?
- Tracking
- More thinking about blogging
- Page about how we work
- More info page on Neontribers
- All 35 issues in backlog: https://github.com/neontribe/www/milestone/8
- Documenting process

### The good?
- New neontribers can add themselves to the website relatively easily.
- Clear understanding of who is visiting and why.
- Process of building the site made us understand who we are better
- New website articulates Neontribe more clearly because of @HedgehogHolly's design
- @HedgehogHolly kept the project moving
- The team when we had a chunk of dev time
- Neontribers can share site with friends and family
- People now can add themselves to the website, this way is now easier because of the website

### The bad?
- Multiple vision on the same thing
- Who can attend the website meeting? Unclear
- Neontribe wider process - add to the on boarding process join Github and people to add themselves to the site.
- Is it possible to run a project without fixed times, codeowners, product owners
- Testing
- Not enough browser and accessibility testing? Did we set expectations and aims?
- Time between planning/thinking and dev too long - loss of momentum. Perhaps too much upfront research.

### The ugly?
- Duration
- Project continuity - assumption that everyone could just drop in and out and still understand what - was going on
- Confusing documentation and project work flow
- Decision making - no record of why things had changed, confusion as to why things had been done
- We were all the customer
- Assumption we would have time to fit building the site in between other builds.

## The Road Ahead

- Schedule sprints ahead of time and we shall work as we do with clients, so every sprint has a sprint, plan, sprint and test.
- New starters can look through the backlog when they start
- Build a process document so people can more easily start. Maybe something especially for new starters

## Actions
- [ ] To write up these notes
- [ ] @harryharrold to look at when people are free and book in the following:
- [ ] UX Sweep/ UAT script: We need to check what stories we have implemented and have we answered those stories before next sprint.
- [ ] Book in future sprint

# all comments below combined into description

**Comment by RpprRoger** [comment]
What we got done: No blog post URL left behind

**Comment by RpprRoger** [comment]
What we got done: The new website exists

**Comment by roseb04** [comment]
- Blog posts are stored and indexed by Google 
- Gives a more accurate impression

**Comment by roseb04** [comment]
The new website has a structured means of enquiring for jobs

**Comment by roseb04** [comment]
Got rid of process page and just have a projects page

**Comment by roseb04** [comment]
## What did we not get done

**Comment by roseb04** [comment]
Tracking

**Comment by roseb04** [comment]
More thinking about blogging

**Comment by roseb04** [comment]
Page about how we work

**Comment by roseb04** [comment]
More info page on Neontribers

**Comment by roseb04** [comment]
All 35 issues in backlog: https://github.com/neontribe/www/milestone/8

**Comment by roseb04** [comment]
Documenting process

**Comment by Nikomus** [comment]
**Great!** New neontribers can add themselves to the website relatively easily.

**Comment by roseb04** [comment]
## Good

- Clear understanding of who is visiting and why. 
- Process of building the site made us understand who we are better
- New website articulates Neontribe more clearly because of @HedgehogHolly's design 
- @HedgehogHolly kept the project moving
- The team when we had a chunk of dev time 
- Neontribers can share site with friends and family
- People now can add themselves to the website, this way is now easier because of the website

## Bad

- Multiple vision on the same thing
- Who can attend the website meeting? Unclear
- Neontribe wider process - add to the on boarding process join Github and people to add themselves to the site.

## Ugly

- Duration
- Project continuity - assumption that everyone could just drop in and out and still understand what was going on
- Confusing documentation and project work flow
- Decision making - no record of why things had changed, confusion as to why things had been done
- Assumption we would have time to fit building the site in between other builds.

**Comment by Nikomus** [comment]
Time between planning/thinking and dev too long - loss of momentum. Perhaps too much upfront research.

**Comment by Nikomus** [comment]
Sad - did we do enough browser and accessibility testing? Did we set expectations and aims?

**Comment by roseb04** [comment]
## The Road Ahead

- Schedule sprints ahead of time and we shall work as we do with clients, so every sprint has a sprint, plan, sprint and test.
- New starters can look through the backlog when they start
- Build a process document so people can more easily start. Maybe something especially for new starters

## Actions

- [ ] To write up these notes
- [ ] @harryharrold to look at when people are free and book in the following:
- [ ] UX Sweep/ UAT script: We need to check what stories we have implemented and have we answered those stories before next sprint.
- [ ] Book in future sprint

**Comment by katjam** [comment]
@roseb04 Can we close this issue? Maybe generate new issues for those actions if we still want to do it that way. @katquatermass @harryharrold Thoughts?

**Comment by katjam** [comment]
Still wondering if we can close this.

**Comment by katquatermass** [comment]
Assigned to @roseb04 for use in review with Rachel - but closing as it doesn't need to be in action lists currently.
