### ISSUE TITLE
Setup CODEOWNERS

### ISSUE THREAD

**Issue by marxian** [neontribe/www#29]
**Create and configure a CODEOWNERS file**

TO enable automatic code-review request to be issued to relevant contributors we'd like to set up the githhub special CODEOWNERS file. Docs are here: https://help.github.com/articles/about-codeowners/

**Plan**
- [ ] Add the file.
- [ ] Set the root owner to `@www` for now.

**Comment by Nikomus** [comment]
@marxian Sounds like a cool idea to me - how would you anticipate files to be allocated later down the road?

**Comment by katjam** [comment]
@RpprRoger reason for closing? I think this will be nice to have so we don't all need to monitor the whole stack all the time.
