### ISSUE TITLE
IE11 hexagon image sizes, including carousel and logo

### ISSUE THREAD

**Issue by zii-67** [neontribe/www#300]
Split from #230 

Size of the images is smaller on IE11 compare to on chrome:

[](url) ![Screenshot from 2019-09-13 15-53-26](https://user-images.githubusercontent.com/54798712/65136901-48ef2c80-da00-11e9-87bd-ae8463d49644.png)

**Plan**
- [ ] change the code of the images size which can be understand IE11.

**Comment by RabidGamer** [comment]
Image size remains the same in IE compared to Chrome
