### ISSUE TITLE
Improve documentation for how deploys work

### ISSUE THREAD

**Issue by roseb04** [neontribe/www#306]
**What needs doing?**

Neontribers have requested more detail about how deployments are done.

**Plan**
- [ ] Turn this task into a learning exercise? 
- [ ] Update the acceptance criteria
- [ ] Update the Readme 

**Acceptance Criteria**
- [ ] Neontribers understand how deployments are made

**Comment by katjam** [comment]
It might be only @RpprRoger who has this info in his head - but worth anyone trying.

**Comment by roseb04** [comment]
@katjam my memory is failing me, @RpprRoger do you recall what this card was about?
