### ISSUE TITLE
IE11 missing separator SVG

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#308]
Split from #230 

The squiggle seperator isn't displayed on IE11. This may have a similar fix to https://github.com/neontribe/www/issues/297

[](url) ![Screenshot from 2019-09-13 15-53-26](https://user-images.githubusercontent.com/54798712/65136901-48ef2c80-da00-11e9-87bd-ae8463d49644.png)
![image](https://user-images.githubusercontent.com/32434620/65970946-545e4100-e45f-11e9-9132-f40b5e7eefdb.png)

## Plan
- [ ] Investigate why the separator graphic doesn't appear
- [ ] Find a way for it to appear on all browsers

## Acceptance Criteria
- [ ] The separator graphic appears on IE11 as it does in other browsers

**Comment by RabidGamer** [comment]
squiggly-dos appearing as intended!

![image](https://user-images.githubusercontent.com/48025294/77921739-1029ed00-7298-11ea-8843-650bd73cd125.png)
