### ISSUE TITLE
Header item distribution

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#309]
Split from #230

The elements of the header aren't distributed the same in IE11 as they are in other browsers.

![logo-placement-homepage](https://user-images.githubusercontent.com/29477363/65252677-50423300-daf1-11e9-91ea-73bbc9b9a91b.png)

## Plan
- [x] investigate and fix... more..

## Acceptance Criteria
- [ ] The layout of the header looks the same as other browsers, or is decided to be OK as is

**Comment by RabidGamer** [comment]
Looks the same in IE! :+1:
