### ISSUE TITLE
Card flip issues

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#310]
Split from #230

There are some visual issues when the card flips in IE. The card may disappear completely, or have content below its bounds. These problems may also exist in Safari.

![image](https://user-images.githubusercontent.com/32434620/68286697-6db76600-0079-11ea-8d5a-442b2638d819.png)

## Plan
- [ ] 

## Acceptance Criteria
- [ ] There are no strange visual effects when the card flips in IE
- [ ] There are no strange visual effects when the card flips in Safari

**Comment by falconx** [comment]
could not reproduce in IE11.

**Comment by SarikaWirtz** [comment]
I could not reproduce it too.

**Comment by zii-67** [comment]
This work well in my IE 11 window 7 virtual machine (Ubuntu).
