### ISSUE TITLE
IE11 and Edge card colours on hover

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#311]
Split from #230

In IE11 the profile cards don't change from black and white to colour on hover as they do in other browsers
In Edge, they don't revert to black and white when not hovered

![image](https://user-images.githubusercontent.com/32434620/65974959-c3d72f00-e465-11e9-8b15-c42a9bf4f55d.png)

## Plan
- [ ] 

## Acceptance Criteria
- [ ] The hover effects are the same in IE & Edge as other browsers

**Comment by RabidGamer** [comment]
colours switch as intended!
