### ISSUE TITLE
Safari - iPad Air, Privacy policy page

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#312]
Split from #230

Safari - iPad Air, Privacy policy page rendering compared to Chrome. This seems to be an issue with how we handle background decoration at smaller screen sizes.
![Screenshot_070319_111321_AM](https://user-images.githubusercontent.com/4446325/60583793-9229cb80-9d83-11e9-9273-191fb02401b0.jpg)

## Plan
- [ ] 

## Acceptance Criteria
- [ ]

**Comment by falconx** [comment]
@Nikomus I'm not sure what the problem is? isn't it just the case that the viewport is smaller and therefore the background collides with the content (which is expected)?

**Comment by Nikomus** [comment]
@falconx I'm not sure - I think perhaps the background is considered part of the margin area outside of the content, so colliding like this is a sort of bug. At this viewport size you can't tell that they're hexagons.

**Comment by falconx** [comment]
my understand is that this is correct. @HedgehogHolly could you confirm if this is the case?

**Comment by HedgehogHolly** [comment]
I believe so, we wanted to make it so that the text was always readable and that was the priority over seeing the hexagons.  

It is only doing that because the view port is causing the hexagons to collide with the text, right?

**Comment by falconx** [comment]
@HedgehogHolly yep, it's just because of the viewport size (you can ignore "Safari" and "iPad" in the title).

**Comment by HedgehogHolly** [comment]
Then yes it is behaving how we would expect/want it to.

**Comment by falconx** [comment]
@Nikomus can we close this issue?

**Comment by Nikomus** [comment]
Looks fixed as of https://github.com/neontribe/www/pull/326 !
![www neontribe co uk_(iPad)](https://user-images.githubusercontent.com/32434620/72428976-c183b100-3786-11ea-9212-84d9922cbb23.png)

**Comment by RabidGamer** [comment]
Tested on iPad Air on safari as per image, appearing as intended.

![image](https://user-images.githubusercontent.com/48025294/77540660-644d5f80-6e9b-11ea-9565-2231df0331fd.png)
