### ISSUE TITLE
Mobile button styling

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#313]
Split from #230

Android - Samsung Galaxy J600FN**
- [ ] Minor styling issue with buttons. this could be related to general background decoration in #312 
![Screenshot_070319_120145_PM](https://user-images.githubusercontent.com/4446325/60586610-53e3da80-9d8a-11e9-85d9-0b9f8ae7c9d0.jpg)

## Plan
- [ ] 

## Acceptance Criteria
- [ ]

**Comment by falconx** [comment]
@Nikomus I'm assuming the issue here is that the colour of the hexagon and the button are the same? not the fact that there is a collision.

A solution could be to add a black border/shadow around the button.

**Comment by Nikomus** [comment]
@falconx Yeah, I think not being sure of the clickable area is the problem. Perhaps the side hexagons should scale with the viewport size so that they remain down the sides of the screen?

**Comment by falconx** [comment]
> Perhaps the side hexagons should scale with the viewport size
possibly, and I played around a little with this but I think we'll still hit a point where this collusion could happen.

I think the black border/shadow solution is more scalable approach but we should see what @HedgehogHolly thinks? :slightly_smiling_face:

**Comment by HedgehogHolly** [comment]
I guess it would more ideal if the hexagons scaled better depending on viewport size but I feel like a border shadow plus maybe a border line, would be more than sufficient for now.

**Comment by falconx** [comment]
:slightly_smiling_face: let's do both then. I'll have the hexagons resize based on the viewport by plugging in the fluid typography algorithm so we can ensure a min/max hexagon size. ans then add a shadow around buttons.

**Comment by katjam** [comment]
Missing AC

**Comment by RabidGamer** [comment]
Hexagons resize as intended and shadow appears when button overlaps :)

![image](https://user-images.githubusercontent.com/48025294/77918182-706a6000-7293-11ea-80e0-2babf3cc9314.png)

**Comment by RabidGamer** [comment]
Hexagons scale and shadow appears as intended

![Screenshot from 2020-03-30 14-38-09](https://user-images.githubusercontent.com/48025294/77918680-20d86400-7294-11ea-9243-e127e5828ab9.png)
