### ISSUE TITLE
Catch-up October 8th

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#315]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from #305 
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board, order/review browser tickets at the bottom of To Do that were split from #230 

**Actions**
- [x] Meet in two weeks time
- [ ] @HedgehogHolly and @RpprRoger to work on docs

**Comment by katjam** [comment]
Closing action moved forward to next catch-ups
