### ISSUE TITLE
Catch-up October 22nd

### ISSUE THREAD

**Issue by roseb04** [neontribe/www#319]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from #305 and #315 
- [ ] Look at work @HedgehogHolly and @RpprRoger have done for docs (NOT DONE)
- [x] Discuss any outstanding PRs
- [ ] Go through the backlog/project board, order/review browser tickets at the bottom of To Do that were split from #230

**Actions**
- [ ]

**Comment by katjam** [comment]
Closing no actions
