### ISSUE TITLE
social media preview for the-tribe page could be better

### ISSUE THREAD

**Issue by Kurgol** [neontribe/www#320]
**Describe the bug**
when you post a link to https://www.neontribe.co.uk/the-tribe/ on social media, the preview is imageless

**To Reproduce**
1. paste a link to https://www.neontribe.co.uk/the-tribe/ on social media

**Expected behavior**
There should be a better preview image, ideally could we get a team photo for this?

**Screenshots**
![neontribe-co-uk-the-tribe-preview](https://user-images.githubusercontent.com/15245142/67086348-6c8cca80-f198-11e9-8959-50bc7e4e5d13.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Chrome
 - Version: Latest stable

**Comment by Kurgol** [comment]
also as Harry pointed out off Github, we could update "colour of tech" to "colour of technology" to get a good Pratchett reference in :)

**Comment by Nikomus** [comment]
@Kurgol It looks like the site-meta-image.png that should be displayed is a 404. It should be a quick fix to change in `gatsby-config.js`.

![image](https://user-images.githubusercontent.com/32434620/67096216-8a195e80-f1af-11e9-9621-9d94ea5ceb35.png)
