### ISSUE TITLE
Catch-up November 5th 🎆

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#327]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from #319
- [x] Look at work @HedgehogHolly and @RpprRoger have done for docs
- [ ] Discuss any outstanding PRs
- [ ] Go through the backlog/project board, order/review browser tickets at the bottom of To Do that were split from #230

**Actions**
- [ ]

**Comment by katjam** [comment]
Closing no actions
