### ISSUE TITLE
Install basic Google Analytics

### ISSUE THREAD

**Issue by katjam** [neontribe/www#33]
**Is your feature request related to a problem? Please describe.**
We'd like to have had at least basic stats for usage of our current site when making decisions on what to include in this new one.

**Describe the solution you'd like**
All the "free stuff" from GA - nothing that's effort to set up in the first instance.

**Describe alternatives you've considered**
Don't think we need anything complicated at this point. Also don't think it'd be worth creating own system to record page views and device usage etc.

**Plan**
- [x] Get Tag Id from #34
- [x] Plug in https://www.gatsbyjs.org/packages/gatsby-plugin-google-tagmanager/
- [x] Consider the page tracking for front end page views tracking correctly

**Acceptance Criteria**
- [ ] I can get some stats from Google Analytics about how people are using the site.

**Comment by roseb04** [comment]
@RpprRoger and I have implemented page views for Gatsby using a plugin for Gatsby. You can view the analytics in the Universal Analytics account and view the events firing by Gatsby-Route-Changes triggering in Google Tag Manager. There is an extension you can get for this in Chrome.
