### ISSUE TITLE
Catch-up November 19th

### ISSUE THREAD

**Issue by katjam** [neontribe/www#330]
**What needs doing?**

**Plan**
- [x] Review incomplete actions from #329 
- [x] Discuss any outstanding PRs (merged one - will wait for appropriate reviews on others)
- [x] Go through the backlog/project board, order/review

**Actions**
- [x] @katjam chase @Nikomus and @HedgehogHolly to move actions from last week to this card or complete them.
- [x] @katjam make a new catch-up card for next week and flag up issues that need discussion
- [ ] @katjam chase old issues in backlog - determine if we need discussion or can close as won't fix. Would be nice to keep out backlog under 35 issues. @jermyk volunteered to help.

**Comment by Nikomus** [comment]
Last action moved to next week's catch-up #334
