### ISSUE TITLE
Catch-up meeting issue template

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#335]
**What needs doing?**
One of the most common actions is to create a new weekly catch-up issue. We can add to the templates we already have to make this easier.

**Plan**
- [x] Add a new catch-up template

**Acceptance Criteria**
- [ ] Pressing "New Issue" provides Catch-up meeting in the list of templates
- [ ] The template has the same structure as weekly catch-up issues

**Comment by katjam** [comment]
Great idea!
