### ISSUE TITLE
Catch-up December 17th

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/www#342]
**Plan**

- [x] Review incomplete actions from #340
- [x] Discuss any outstanding PRs
- [x] Go through the backlog/project board, order/review

**Actions**

- [ ] @RpprRoger to check in on "@jermyk chase old issues in backlog - determine if we need discussion or can close as won't fix. Would be nice to keep out backlog under 35 issues." [Jan 7 Katja taking it over]
- [ ] @RpprRoger to think about how things get moved to the todo list, during the catchup we could add a note for why it's bumped to "todo" [jan 7 adding to process doc]
- [ ] @RpprRoger Look for a new design lead to take on the neontribe website
- [x] @katquatermass See if Holly has time to "fully" to review #324, i.e. add a request changes mark
- [x] @katquatermass Update [`catch-up.md`](https://github.com/neontribe/www/edit/master/.github/ISSUE_TEMPLATE/catch-up.md) to be clearer what to do with PRs in the plan list during the meeting
- [x] @katquatermass review @RpprRoger's Contributing doc https://github.com/neontribe/www/pull/338
- [ ] @RpprRoger ask @jermyk to check ie11 bug on preview: https://github.com/neontribe/www/pull/331 [Jan 7 Rose can see squiggle on ie11]
- [ ] @RpprRoger to finish up https://github.com/neontribe/www/pull/325

**Comment by katquatermass** [comment]
Re #324 @falconx has revised the fix so B/W v Colour is now correct. Holly has no time left but also doesn't need to do any more with this.  I am not familiar enough with what the end of an issue should look like to know if it fully merged or not yet!

**Comment by katquatermass** [comment]
I left pull requests on catch-up.md to see if folk thought my changes were overkill or not. And because I am practising using Git!
