### ISSUE TITLE
Need package updating 

### ISSUE THREAD

**Issue by zii-67** [neontribe/www#345]
**Describe the bug**
Error occur notified by Zeit checks, node.js need to be update.

**Expected behavior**
PR will be able to merge in.

**Screenshots**
![Screenshot_20200113_152634](https://user-images.githubusercontent.com/54798712/72268088-17d2e180-3619-11ea-9458-cffa7744c91b.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]

**Comment by RabidGamer** [comment]
Have confirmed Node.js was successfully updated.
