### ISSUE TITLE
Catch-up January 14th

### ISSUE THREAD

**Issue by katjam** [neontribe/www#347]
**Plan**

- [x] Review incomplete actions from #344  and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [ ] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review issues for new candidates to bring forward on to board.
- [ ] Think about which labels we need/ use.

**Actions**

- [x] @katjam remove backlog milestone and add backlog column to end of project board. New issues will not be added to a project. Add to weekly agenda to consider issue not yet in a project - to be added to backlog or to do column.
- [ ] @katquatermass Add to process doc things get moved to the todo list, during the catchup we could add a note for why it's bumped to "todo"
- [ ] @katquatermass Speak to @RpprRoger about getting contributors doc finished and resolve comments https://github.com/neontribe/www/pull/338/files
- [ ] @katquatermass will generate a copy issue to address the orphan 'need' on home page from #184 
- [ ] @katquatermass will review the different documentations and see where there is overlap contradictions pathways

**Comment by katjam** [comment]
I'd like to propose that we get rid of the `to do` column on the project board - in preference of keeping the backlog as an ordered list. This way we don't have to maintain 2 lists in sync and we can keep the project view for issue progression.

When people add things - place in approximate priority.
When people grab things - take from top of backlog.
Issues from thebacklog that are added to the project board should land in `In progress`

**Comment by katquatermass** [comment]
Agree with simplifying to one list. Disagree with "place in approximate priority" - that's a group decision. Thing being added should go into the bottom of the backlog until it has been discussed at a weekly meet?

**Comment by katjam** [comment]
Sounds like a plan. Sometimes with bugs it's better to just get them fixed, but I think you are right, generally speaking the group should decide, so take that part out.

I think new issues automatically go in at the bottom of the list - but we could have a label that flags it was being new so that they are the first issues to be considered if we are rushing the meeting.

**Comment by Nikomus** [comment]
Definitely in favour of not maintaining two ordered lists that don't synchronise. I'm not sure if it's better to keep the milestone and have the project board only for issues that are active, or to remove the backlog milestone and have everything on the project view in prioritised and new/unprioritised  columns.

**Comment by katquatermass** [comment]
That second description is my pref I think  - two columns on project board
one prioritised one for new things (but am aware that's because I LIKE
boards because Trello is familiar ground)


*Kat QuatermassService and Strategy Design*
Neontribe
Kat@neontribe.co.uk
0789 1487375

**Comment by katjam** [comment]
If we do that it'll be best to ditch the milestone altogether - and it'll mean that we only have to look in one place - but the board may get cluttered with non-priority stuff. If that starts to bug us, we can maybe move that column to the end of the list.

**Comment by katjam** [comment]
I kind of see the project board as a place for stuff that is in progress - but I also see the advantage of having everything in one place.

**Comment by katjam** [comment]
@katquatermass @zii-67 As agreed, I have added a new backlog column to the end of the project board and deleted the milestone.

We will need to update process documentation appropriately.

During catch-up call:
- we should aim to review issues with `is:open is:issue no:project ` to see if we want to add them. If added to project they automatically turn up in the backlog column. If we want to promote them, we can move to the `Top priority` column.
- we should aim to keep the `Top priority` to an agreed number of issues (5 or 10?)

**Comment by katquatermass** [comment]
https://miro.com/app/board/o9J_kv_Rw6Y=/

**Comment by katquatermass** [comment]
Unfortunately, reflected on a copy solution to #184 and realised its not really valid due to responsiveness (unless we set a series of sizes at which we care and I check them all individually - I think an orphan will look worse the wider the screen size - on a mobile phone it'll barely register for people as an issue, so we could do this, but I'd need to know how many formats to check)

**Comment by katquatermass** [comment]
Would like to recommend we do top priority and backlog review before talking about the actions relating to contributing docs, so that getting that lined up does not stall progress.

**Comment by katjam** [comment]
@katquatermass Do we want to move outstanding actions forward into the next card and close this one?

**Comment by katjam** [comment]
@katquatermass Closing to push on to #353
