### ISSUE TITLE
Catch-up Jan 21st

### ISSUE THREAD

**Issue by katjam** [neontribe/www#352]
**Plan**

- [x] Review incomplete actions from #347 and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [x] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.
- [x]  Think about which labels we need/ use

**Actions**

- [ ] @katquatermass to add to documentation the process for labeling cards as "high priority - and therefore in Top Priority list - but not yet ready to develop as it needs discussion"
- [x] @katjam go through the backlog - add/remove appropriate labels to help with @katquatermass process documentation

**Comment by katquatermass** [comment]
We looked at cards in the top priority list and found three categories:
1) cards ready to action
2) cards not ready to action, but where the card has enough documentation to be sure it is top priority
3) cards that we're not certain are top priority - these, for now are going to the top of backlog - for future where meetings are using the backlog sort and document process it should not be necessary any more to do this. If one meeting decides something makes it into the priority list and documents that then it should not be possible for a later meeting to second guess that (there will probably be the odd exception with super compelling evidence, but as a general rule)

**Comment by katquatermass** [comment]
I have not done any documentation work since the layout map shown on #347
I want to co-write documentation with a dev, but I don't know if anyone has time.

**Comment by katjam** [comment]
@katquatermass I will move the action forward and close this issue.

I'll also amend it so it says schedule a time with a dev to ... do the thing.
