### ISSUE TITLE
Catch-up 11th Feb

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#358]
**Plan**

- [x] Review incomplete actions from #353  and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [ ] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**

- [ ] @katquatermass and @RpprRoger are part way through documentation and will continue
**Documentation improvements**
- [x] Add the process for labeling cards as "high priority - and therefore in Top Priority list - but not yet ready to develop as it needs discussion"
- [x] Add to process doc things get moved to the todo list, during the catchup we could add a note for why it's bumped to "todo"
- [ ] Ensure document consistency

**Comment by katquatermass** [comment]
Closed via #362
