### ISSUE TITLE
Catch up 25th Feb

### ISSUE THREAD

**Issue by katquatermass** [neontribe/www#362]
**Plan**

- [ ] Review incomplete actions from #[previous catch-up] and decide whether to carry over or change the action
- [ ] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [ ] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**

- [ ] @katquatermass and @RpprRoger are part way through documentation and will continue
Documentation improvements 
- [x] @charlesstrange2 needs to approve change he requested on pullrequest for #354 Harry's Blog
- [ ] @katquatermass and @RpprRoger to take @zii-67 #348 and connect it with other documentation about making pull requests and add a bit of clarity that a merge IS a deploy
- [x] Next meeting will be extended (11am - 12pm) to introduce Rose & Rachel doing a review of "how well did we meet our original user needs and company ethos thinking"

**Comment by harryharrold** [comment]
Next week, @roseb04  and rachel will talk over a bit of work to check how we're doing on our existing user stories, and identify next steps for a slightly longer scheduled piece of work on the site.

**Comment by katjam** [comment]
@katquatermass @robpre @zii-67 Assuming you are still in progress on the documentation

**Comment by katjam** [comment]
Closing and will promote forward the outstanding tasks
