### ISSUE TITLE
Anonymise or delete the prototype 

### ISSUE THREAD

**Issue by robpre** [neontribe/www#368]
**Describe the bug**
We have a version of the website in its beta phase. https://www.neontribe.co.uk/prototype/

We should decide to anonymise or delete.

**To Reproduce**
Tell others how to reproduce the problem behavior
For example:
1. Go to https://www.neontribe.co.uk/prototype/
2. Click on the tribe
3. Scroll down to Andy
4. See Andy

**Expected behavior**
No neontribe employees are available so we don't need to keep them in sync

**Screenshots**
![image](https://user-images.githubusercontent.com/1443409/76007464-fbab3c80-5f05-11ea-9a63-e7298d023269.png)

**Comment by katjam** [comment]
I think this is a dupe of #285
