### ISSUE TITLE
Meeting about timelines

### ISSUE THREAD

**Issue by katjam** [neontribe/www#37]
**What needs doing?**
Meeting about timelines
Attended by Katja, Kat, Nick, George, Harry, Andy, Holly, Steph

**Agenda:**
1) Update on look and feel - what is needed next?
2) Update on where technical thinking is - is any more work needed pre sprint 1?
3) Decide if/how and when we are going to attempt a "follow the users flow" prototyping session 
4) Set a date for start of sprint scoping to MVP session (based on all stories and prototypes so far and the result of 3 (possibly with Katja in Norwich if feasible?)
5) set a first sprint schedule

Follow On if time:
1) Web adjacent projects - eg Twitter etc - people to take on actions
2) Current website update (copy amends/explorations that will have value for future sites)

**Comment by katjam** [comment]
- Harry and Kat to look at the 9 user story priorities
- Set a date for coming to Norwich week of 21st (Katja get flights)

**Comment by katjam** [comment]
@katquatermass I guess it's just those actions in my comment. But did you take better notes?  Please add here and close I guess. I'll do my flights thing.

**Comment by katquatermass** [comment]
1. Look and feel work is to be paused until content progressed further
2. Technical work can continue, and has several distinct tasks so it is possible for different devs with free time to progress those  
3. Schedule two sessions during Katja's visit - one to explore user flow one to finally scope for first sprint
4. Harry and Kat to break down stories into smaller chunks to prioritise prior to flow session
