### ISSUE TITLE
Define YouTube protocols

### ISSUE THREAD

**Issue by katjam** [neontribe/www#4]
# Description
Define how we want to use You tube and make it possible

# Plan
- [ ] Find out who has access to Youtube
- [ ] Agree copy for profile
- [ ] Edit profile with up to date copy and link to website
- [ ] OR - use it to host unlisted  videos and link to them but not have a feed

**Comment by katjam** [comment]
Andy Barnes11:30 AM
yeah actually as a twitch/youtuber probaby what neontribe wants is for all our videos to be unlisted, but viewable with a link (Then we can embed the content in pages, but we won't have people browsing through our "feed")
Kat Quatermass11:31 AM
Genius Andy - when I'm next in the office I'll pick your brains!
You11:31 AM
@andy Yes that sounds smart

**Comment by katquatermass** [comment]
Goal - ask Andy for wider recommendations and then set implementation schedule. How would we keep track of other people's videos that feature us, for example

**Comment by Kurgol** [comment]
When you upload a video on youtube, you can set the visibility to:

public // everyone can see your vide
private // you assign viewers by their youtube account details
unlisted // your video will not appear in search results, or show on your chan, only those with link can view

There isn't really @tagging on youtube so it's unlikely that we would catch others mentioning us other than by doing some manual digging around (searching for our name, tags)

**Comment by Kurgol** [comment]
When creating the youtube channel we should do it by creating a "brand" account rather than a personal account:

visit youtube and sign in (this should be done with a neontribe/business account, ie one the company owns rather than a users)
click the picture icon in the top right then the gear icon from the dropdown: account > settings
click "See all my channels or create a new channel"
click "+ Create a new channel"
choose brand name, presumably "Neontribe" > create
set additional permissions to other users to manage the chan.

**Comment by katjam** [comment]
@andybarnes Go for it.

**Comment by roseb04** [comment]
I think @tobybatch has the Neontribe youtube account based on the video content (ie it seems to be just Toby) - https://www.youtube.com/user/neontribe

**Comment by katjam** [comment]
@RpprRoger Reason for closing? I think this needs sorting out.

**Comment by katjam** [comment]
@andybarnes @katquatermass @Kurgol - Did we ever figure out how to get hold of the Neontribe You Tube.

Do people still think this is important - or should we close?

**Comment by Kurgol** [comment]
I never found it, but think one of the directors controls it there are only two videos up on the chan. https://www.youtube.com/user/neontribe

**Comment by katquatermass** [comment]
Moved to the Internal Projects guide as not central to website development
