### ISSUE TITLE
Documenting the Flow workshop and MVP session

### ISSUE THREAD

**Issue by katjam** [neontribe/www#40]
**What needs doing?**

**Plan**
- [x] Add photos from session - post-its and prototypes
- [x] We have MVP elements - try to list here

**Comment by katquatermass** [comment]
https://realtimeboard.com/app/board/o9J_kyNvcm0=/   Should be available for all to comment and RTB members to edit.  I do not have pictures of the detailed post it journeys for the other groups.

**Comment by katquatermass** [comment]
MVP Element list superceded and moved to #43
