### ISSUE TITLE
Catch-up meeting 12 Feb 2019 10:00

### ISSUE THREAD

**Issue by katjam** [neontribe/www#42]
**Progress!**

**Agenda**
- [x] Report on actions from #41 
- [x] Create actions

**Actions**
- [ ] Make a plan for usability testing prototype in Exeter @katjam 
- [x] Go through and close and archive issues @katquatermass 
- [x] Annotate prototype images with outstanding questions prior to testing @katquatermass

**Comment by katquatermass** [comment]
Suggegst: Postpone action 1 until after next meeting - as significant discussions still required to get protoype ready for testing?  @katjam ?

**Comment by katjam** [comment]
@katquatermass  I agree we need some changes made before we test - but maybe making a plan with a deadline will mean that we can move forward. At some point we just need to go ahead and test what we have.
