### ISSUE TITLE
Catch-up 10th June

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#436]
**Plan**

- [x] Review incomplete actions from #431 and decide whether to carry over or change the action
- [x] Discuss any outstanding PRs and either approve, comment OR assign someone an action to review
- [ ] Go through the to do list on the project board, order/review. IF list is short or down to low priority items or IF someone has asked the meeting to discuss a specific new issue, also review backlog for new candidates to bring forward.

**Actions**

- [x] @Nikomus to do or arrange for - Format wiki https://github.com/neontribe/www/wiki/Handling-automatic-pull-requests-(renovate)
- [ ] Carried forward 11 meetings: @katquatermass and @robpre are part way through documentation and will continue on #307
- [ ] @katjam speak to @marxian about howmuch of an issue it is that we can't get build logs for fails in PRs. The work-around is local pull of branch to check
- [x] @katjam pick off the easy to review auto bot PRs and encourage them gently in

**Comment by katjam** [comment]
@katquatermass @robpre do we want to draw a line under #307 and raise a new set of doc improvement cards? It feels like it's maybe gone stale & is maybe not a priority for time spending.
