### ISSUE TITLE
Cookie banner display bugs

### ISSUE THREAD

**Issue by katjam** [neontribe/www#438]
**Describe the bug**
- banner flashes up briefly if declined / accepted previously.
- banner is yellow on mobile
- other small styling improvements as appropriate

**Expected behavior**
- init banner as collapsed or wait for state before rendering anything at all
- mobile colour same as desktop

**Screenshots**
![Screenshot_20200610_135828_com android chrome](https://user-images.githubusercontent.com/861172/84270610-db9da180-ab22-11ea-8e12-49fc38f385e5.jpg)

**Comment by falconx** [comment]
This will now be fixed by #465
