### ISSUE TITLE
Catch Up Meeting 26th February

### ISSUE THREAD

**Issue by katquatermass** [neontribe/www#45]
**Progress**

**Agenda**
- [ ] Report on actions from #44 

**Actions**
- [x] Confirm dates with Holly. Week beginning 11 March better for @Nikomus and @katjam but if @HedgehogHolly can only do week of 4th that is also OK.

**Comment by katjam** [comment]
Meeting did not take place but @katquatermass @katjam @Nikomus @HedgehogHolly discussed booking the usability testing sessions in exeter - we are ready to move on that.

**Comment by katjam** [comment]
Done. Holly is here!
