### ISSUE TITLE
No focus style on "hello@neontribe.co.uk" Get In Touch link

### ISSUE THREAD

**Issue by falconx** [neontribe/www#468]
**Describe the bug**
There is no visible focus style on "hello@neontribe.co.uk" Get In Touch link

**To Reproduce**
Apply focus to the hello@neontribe.co.uk link under the "Get in touch" header found on the homepage.

**Expected behavior**
An outline should appear, as you'll see when other elements are focused.

**Comment by Nikomus** [comment]
This element isn't in the site anymore.
