### ISSUE TITLE
Usability testing the MVP paper prototype in Exeter

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#48]
**What needs doing?**
Create testing scenarios that follow the userflows from #40 
Test with users the prototype https://github.com/neontribe/www/issues/43

**Scenarios**

1. You are a grant officer for a charity, the company you are funding wants to hire Neontribe. Decide whether you trust us to do the job.

1. You are someone who has just finished a coding bootcamp, you met a developer who said their company was hiring, you remember a few details but not company name. Get in touch with a specific person.

1. You are a returner to work, you've heard we do work for charities. Find out if neontribe hire interns.

1. You are a 16 year old in Manchester, you want to work for a tech company and searched google, you were deep linked to neontribe.co.uk/people. Find out if you can do work experience with us.

1. You are a tech conference organiser, someone sends you a link to neontribe.co.uk/projects. Identify a speaker by finding out which tools/frameworks we use.

1. You are a project manager, you have a work experience student for a week, you'd like to give them a day with a web development company, you know there are three in your building. Find out if we are a suitable company to approach

1. You are a project manager, you're running late for a meeting with us, you only have a link in an email that leads to neontribe.co.uk/projects. Find a phone number to call.

1. You run a co-working space, someone rings up to get in contact Katja from neontribe, you haven't seen her in the office for a few days. Find a way to contact Katja using the website.

1. You run a co-working space, a potential tenant is asking about other web development companies in the space you think neontribe are a web development. Find out what type of projects we do.

1. You are a returner to work, just finished a bootcamp find out if you would fit in with the people at Neontribe.

**Comment by HedgehogHolly** [comment]
**The three user missions:**

- Find someone you met at a conference and decide whether to follow up with the company
- Decide whether you trust the company enough to approach them to deliver a project
- Decide whether you feel this company has the right diversity of people to work with

**Comment by katjam** [comment]
We'll test with the 'footer' on every page and the 'footer' only on the landing page.

& Include a deep linked one with the objective of getting in touch.

**Comment by HedgehogHolly** [comment]
**Scenario 1: you are a grant officer for a charity, the company you are funding wants to hire Neontribe. Decide whether you trust us to do the job.**

![20190313_144356](https://user-images.githubusercontent.com/41140803/54295316-a9f9fb80-45aa-11e9-91d8-167af350cee9.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 2: You are someone who has just finished a coding bootcamp, you met a developer who said their company was hiring, you remember a few details but not company name. Get in touch with a specific person.**

![20190313_145908](https://user-images.githubusercontent.com/41140803/54295438-eded0080-45aa-11e9-983f-69ade1482de3.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 3: You are a returner to work, you've heard we do work for charities. Find out if neontribe hire interns.**

![20190313_151406 (1)](https://user-images.githubusercontent.com/41140803/54295556-2e4c7e80-45ab-11e9-96a6-74e6c5dc2c39.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 4: You are a 16 year old in Manchester, you want to work for a tech company and searched google, you were deep linked to neontribe.co.uk/people. Find out if you can do work experience with us.**

![20190313_151414](https://user-images.githubusercontent.com/41140803/54296032-0e698a80-45ac-11e9-8e53-6093b786ff7f.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 5: You are a tech conference organiser, someone sends you a link to neontribe.co.uk/projects. Identify a speaker by finding out which tools/frameworks we use.** 

![20190313_151615](https://user-images.githubusercontent.com/41140803/54296161-4a9ceb00-45ac-11e9-8960-3f93f0ba17f8.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 6: You are a project manager, you have a work experience student for  a week, you'd like to give them a day with a web development company, you know there are three in your building. Find out if we are a suitable company to approach**

![20190314_111120](https://user-images.githubusercontent.com/41140803/54354939-bab07d00-464f-11e9-832a-79ba2bb37002.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 7: You are a project manager, you're running late for a meeting with us, you only have a link in an email that leads to neontribe.co.uk/projects. Find a phone number to call.**

![20190314_111332](https://user-images.githubusercontent.com/41140803/54355020-ec294880-464f-11e9-8815-cfcebe0f7adf.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 8: You run a co-working space, someone rings up to get in contact Katja from neontribe, you haven't seen her in the office for a few days. Find a way to contact Katja using the website.**

![20190314_113406 (1)](https://user-images.githubusercontent.com/41140803/54355090-20046e00-4650-11e9-8e1e-88ea53bd8fa0.jpg)

**Comment by HedgehogHolly** [comment]
**Scenario 9: you run a co-working space, a potential tenant is asking about other web development companies in the space you think neontribe are a web development. Find out what type of projects we do.**

![20190314_113607](https://user-images.githubusercontent.com/41140803/54355169-488c6800-4650-11e9-85d2-5bee879c96e6.jpg)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/54602877-c4185b80-4a3a-11e9-8be6-1cdfb6ba4a49.png)

**Comment by katjam** [comment]
Changes proposed in #49

**Comment by katjam** [comment]
Changes proposed in #49
