### ISSUE TITLE
Define Facebook protocols

### ISSUE THREAD

**Issue by katjam** [neontribe/www#5]
Define how we want to use Facebook and make it possible

# Plan
- [x] Find out who has access to Facebook
- [x] @harryharrold to add more people as admins/editors
- [x] Update profile pic to fit in circle icon, delete the other 4 versions
- [x] Turn off messaging to channel contact through website
- [x] Clear out notes and test posts
- [ ] Agree copy for profile
- [ ] Edit profile with up to date copy and link to website
- [ ] Big pinned post of new website, when it's live

# People to be admins:
- [ ] @katquatermass 
- [ ] @Nikomus 
- [ ] @Kurgol 
- [ ] @harryharrold 
- [ ] @roseb04 (if she can find her Facebook account)

**Comment by katquatermass** [comment]
Our current recommendation for Facebook is:

1) we do not want to actively engage with using it. Facebook is making it harder and harder for organisations to get effective reach without paying for it, and we have no core stories that require Facebook to be met.
2) we do need to have a presence - because some people search Facebook for things instead of the internet, and because if not some form of scraping will likely create our presence.
3) We believe we can meet this with a profile that emphasises that we do NOT update Facebook and redirects to website.
4) We could enhance that basic profile with some images of the way we work to give people reason to progress through to website

**Comment by katquatermass** [comment]
@katjam you have a "thumbsdown" above - do you want to elaborate a bit?

**Comment by katjam** [comment]
@katquatermass Yep - is basically the shorthand for what you said - don't wish to engage with facebook at all. We probably need an official page - so that an unofficial one is not created - but leave at that with signpost to our website.

**Comment by roseb04** [comment]
We found out who owns the Facebook page and it is Harry!

**Comment by Nikomus** [comment]
Some more possible actions to add to plan:
- [ ] Add more people as admins
- [ ] Update profile pic to fit in circle icon, delete the other 4 versions
- [ ] Turn off messaging to channel contact through website
- [ ] Clear out notes and test posts
- [ ] Big pinned post of new website, when it's live

**Comment by katquatermass** [comment]
Agree to all. @roseb04 does not have facebook - so we need volunteers who don't mind Harry making admins so we can do that...  Nick - shall we both?

**Comment by roseb04** [comment]
@Nikomus those suggestions sound really good to me. 

@katquatermass I have set up a Neontribe Facebook now for work purposes, but it would nice if we had multiple people who could be admins. @Nikomus would you be interested?

**Comment by Kurgol** [comment]
I agree with the not using facebook theme happening in this thread. I don't mind being an admin if we are having one.

**Comment by roseb04** [comment]
I've added a list of people who are happy to be admins :)

**Comment by harryharrold** [comment]
I've added Kat as Admin - happy for more to be added too.

**Comment by Kurgol** [comment]
@katquatermass are you going to add the rest (now you have the *power*)

**Comment by katquatermass** [comment]
Once I've checked what stopped Harry doing so in case is hard for me too!
Might be around having to be FB friends or something. But today mostly am
on trains and in meetings, so more likely tomorrow when in office.

**Comment by katquatermass** [comment]
Hmmm - I cannot find my existence as admin.. I am looking here, it does not seem to know me  https://www.facebook.com/Neontribe-102061474221/
(and have no messages for any other Neontribe location thing) sorry @harryharrold any ideas?

**Comment by Kurgol** [comment]
@katquatermass you can find the instructions for adding people to the admin group here https://www.facebook.com/help/187316341316631?helpref=related (if you can't access those options it's likely we'll need to poke via @harryharrold's account).

**Comment by katquatermass** [comment]
Yep, its not in my list of pages I manage, so I think the action is still
with Harry

**Comment by katjam** [comment]
@katquatermass suggests @andybarnes helps @harryharrold set up the admins next time they are together in the office.

**Comment by Kurgol** [comment]
I will try and assist @harryharrold the next time he's in the office, obviously I can't do this without accesss to his facebook account.

**Comment by katquatermass** [comment]
Lots of progress thanks to lots of people. Next task is a copy draft for profile. @harryharrold d'you want to have a look at it? You could take my "heading in the right direction but not there yet" stuff from people and projects pages of current website as a starter?

**Comment by katjam** [comment]
@katquatermass @harryharrold @Nikomus Has the facebook page / account been sorted out with a few admins and we can close this?

If there is still an issue about the content there - then maybe we can raise a fresh issue?

**Comment by katquatermass** [comment]
I think @Kurgol has the updates on this. He was doing something with the admin status on the account and finding Facebook unhelpful - not sure where it ended up.

**Comment by katquatermass** [comment]
Could be reopened on Internal Projects board and removed from website thinking though

**Comment by katjam** [comment]
@katquatermass That is an ace idea! Can you do that please? Also with the linked in and youtube ones... maybe even a single card for all 3?

**Comment by katquatermass** [comment]
Moved to Internal Projects Trello
