### ISSUE TITLE
Catch-up meeting 23rd of April

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#52]
**What needs doing?**
https://meet.google.com/fnw-uqxr-bhw

**Agenda**
Review incomplete actions from #50 below:
- [x] Agree a timeline to aim for
- [x] Nominate a product owner and/or project manager for a period of time (could be passed on week to week or longer term and reviewed week to week)... discuss, am not sure how/ if would work but we need someone to make decisions and to someone keep project moving.
- [x] Review @HedgehogHolly work in branch 

**Actions from #50**
- [ ] (Inherited from #49) Attempt to get someone to tackle some of the current issues 
- [ ] Set up a catch up to review these actions for next Tues 12:15
- [ ] ...

**Actions**
- [x] Set next date - Tuesday before standup;  in a fortnight - make a calendar entry - @charlesstrange2 Make Catch-up issue for the next one.
- [ ] Round of design checking PR (companywide)
- [ ] Review @ob6160 PR about wordpress/gatsby (companywide)
- [x] Create copy issues based on design @HedgehogHolly 
- [ ] Harry will product own for this next stage
- [ ] @HedgehogHolly  to work on item 4 of card #51 "Produce UI then decide what other support structures are needed to get it to a live deploy"
- [x] Create a space to make the website public; github pages - @HedgehogHolly (also ask @katjam)
- [x] setup milesotne "Public release by July" - Harry

**Comment by katjam** [comment]
Done. closing.
