### ISSUE TITLE
Remove cookie banner and transfer to Plausible

### ISSUE THREAD

**Issue by rosejbon** [neontribe/www#525]
**Plan:**

- [ ] remove cookie banner and google analytics
- [ ] add plausible script

**Acceptance criteria:**

- [x] Users are not tracked by Google Analytics
- [x] There is no cookie banner
- [x] Analytics are collected on [Plausible](https://plausible.io/neontribe.co.uk)

**Comment by rosejbon** [comment]
Related PR: https://github.com/neontribe/www/pull/526

**Comment by Nikomus** [comment]
Closed by #526
