### ISSUE TITLE
Front Page: Core Values

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#55]
### **What needs doing?**
A small paragraph under the illustration that sums up Neontribe's core values. The paper prototype had the suggested words from Kat that would be good to include in the paragraph: 

- Problem Solving
- Digital
- User-led
- Working Together

### Word count suggestion
**Minimum:** 40 words
**Maximum:** 75 words

### Image of where text will be
![Screenshot 2019-06-19 at 15 29 36](https://user-images.githubusercontent.com/41140803/59774270-16ba1b80-92a7-11e9-9747-4158c3d7d04b.png)

### Related user stories
- As Brian, I want to understand the process neontribe use to deliver projects so that I feel confident they can deliver on our project.
- As Brian, Jess and Terrance, I want to get the impression that Neontribe know what they are doing so that I feel confident in working with them.

**Comment by katjam** [comment]
Could be important to link to research here - there were clear things we wanted to convey with this copy - besides the key words.

**Comment by harryharrold** [comment]
@HedgehogHolly - where's the research @katjam is talking about?

**Comment by HedgehogHolly** [comment]
@harryharrold the only thing I can think of is the results from out user testing - https://github.com/neontribe/www/issues/48

**Comment by harryharrold** [comment]
Fascinating that only one of them stayed on the home page - they all went elsewhere at an early opportunity, and only one of them seemed at all interested in the home page content.

**Comment by harryharrold** [comment]
"Neontribe is a digital agency working in user research, software development and design. We're agile by instinct, and user-centred in our design. We work together to identify and deliver on user need."
