### ISSUE TITLE
How We Work: Our Process

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#57]
### **What needs doing?**
**Confirm the name of this section** How We Work or Our Process, something else?
The paragraph should be a description or general overview of our working process. Including how we work with funding bodies.

### Word count suggestion
**Minimum:** 50 words
**Maximum:** 140 words

### Image of where text will be
![Screenshot 2019-05-22 at 10 11 49](https://user-images.githubusercontent.com/41140803/58162420-0c8e0880-7c7a-11e9-9426-9f1bf997832a.png)

### Related user stories
- As Brian, Jess and Terrance, I want to get the impression that Neontribe know what they are doing so that I feel confident in working with them.
- As Brian, I want to understand the process neontribe use to deliver projects so that I feel confident they can deliver on our project.
- As Jess, I want to see that Neontribe have worked with funding bodies before so that I can strengthen my funding application

**Comment by harryharrold** [comment]
"The things we do."

"Neontribe is a digital agency working in user research, software development and design. We've got a national reputation for our work in tech-for-good, and an international reputation in travel and tourism. We're agile by instinct, and user-centred in our design. Our work identifies the issues organisations have and finds ways to help them out."
