### ISSUE TITLE
Define Linkedin protocols

### ISSUE THREAD

**Issue by katjam** [neontribe/www#6]
# Description
Define how we want to use Linkedin and make it possible

# Plan
- [ ] Find out who has access to Linkedin
- [ ] Agree copy for profile
- [ ] Edit profile with up to date copy and link to website

**Comment by katjam** [comment]
@harryharrold I'm guessing current use of linked in is through your account or @amandaneontribe 's

I don't know what the normal is for accounts there - but is there a company vs personal concept or is it about people?

If either of you (or another linkedin user) would like to action something, please use this card. If not, I think we can close it as stale.

**Comment by katquatermass** [comment]
Moved to internal projects trello
