### ISSUE TITLE
The Tribe: Introduction

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#67]
### **What needs doing?**
A small paragraph at the top of The Tribe page introducing who we are as a company. 
### Word count suggestion
**Minimum:** 40 words
**Maximum:** 100 words

### Image of where text will be
![Screenshot 2019-06-19 at 15 34 54](https://user-images.githubusercontent.com/41140803/59774717-d9a25900-92a7-11e9-8bd7-27c6f8b3f2e5.png)

### Related user stories 

- As Shaii, I want to see a culture that supports individuality so that I know that I will be able to fit in.

**Comment by katjam** [comment]
Could be useful to link to user stories we need to cover with this copy. We have some findings from testing and also assumptions from before that.

**Comment by harryharrold** [comment]
@HedgehogHolly re "We have some findings from testing and also assumptions from before that." - could you point me at these?

**Comment by harryharrold** [comment]
"Neontribe is an eclectic group of individuals with interlocking skills and enthusiasms. Without our differences, we'd not have our strength."
