### ISSUE TITLE
The Tribe: Join The Tribe

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#69]
### **What needs doing?**
A small paragraph explaining how joining neontribe works, which leads to the survey form. Maybe benefits to joining? 

### Word count suggestion
**Minimum:** 50 words
**Maximum:** 130 words

### Image of where text will be
![Screenshot 2019-05-22 at 10 33 41](https://user-images.githubusercontent.com/41140803/58164113-1b29ef00-7c7d-11e9-8cbf-f2d6ab0c9315.png)

### Related user stories 

- As Mrs Jones, I want to see whether Neontribe take on interns/students and how they look after them, so that I know that I won't waste my time contacting them.
- As Shaii, I want to know how to apply for a job at Neontribe so that I can apply

**Comment by harryharrold** [comment]
"We’re always happy to hear from people who like the sound of Neontribe, and want to grow their skills as a developer, or in user research or product management. Maybe you’re already experienced, or maybe you're just getting started. If you have an eagerness to learn more and want to be part of a great company, contact us with a short description of the skills you have and the skills you want to gain and we’ll let you know if we think there’s a place for us to start talking. That's it."

**Comment by harryharrold** [comment]
@HedgehogHolly - cut and pasted from elsewhere. Good words.

**Comment by jermyk** [comment]
@harryharrold Does it mean that the fact that we've not mentioned software testing in the above means my job's safe or are we generally only interested in the skills mentioned?
