### ISSUE TITLE
Define Twitter protocols

### ISSUE THREAD

**Issue by katjam** [neontribe/www#7]
## Plan
- [x] Twitter guidelines
- [ ] Set up Twitter rota?

**Comment by Nikomus** [comment]
We can use a scheduler like [Tweetdeck](https://tweetdeck.twitter.com/) to help spread out posts and allow other people to check things over before they're sent out.

**Comment by katquatermass** [comment]
https://docs.google.com/document/d/1zKDYz1YsIY08Khwk6mnm0dkmoOv8LYVXLdxwDPBkE78/edit#

**Comment by katquatermass** [comment]
So far both Rose and I schedule tweets to Neontribe account via Tweetdeck. I haven't explored whether it is possible to see others scheduled stuff by refreshing if more than one person is scheduling at once. Or actually I think maybe we checked and it does.   Do you have the account passwords so you can too @Nikomus ?

**Comment by Nikomus** [comment]
@katquatermass my account is linked so I can act as Neontribe through Tweetdeck, but I don't know the credentials to sign in via another client.

**Comment by roseb04** [comment]
I can't see any reason why we shouldn't all be able to schedule tweets simultaneously using Tweetdeck. We should test it to check this. 

I have the login details for Twitter. If we found a way to share this securely we could use Twitter's interface as well as Tweetdeck. I personally use both and Tweetdeck,

**Comment by katquatermass** [comment]
Current securely share = call Nick on hangouts and tell him I think!

**Comment by roseb04** [comment]
Nick and I tested and we can schedule tweets simultaneously!

**Comment by Nikomus** [comment]
@katquatermass @roseb04 As the guideline will be a living document, do we think we can close this issue now?

**Comment by Nikomus** [comment]
@katquatermass  Would we have enough to be worth a whole board? Maybe pinned to the Slack channel?

**Comment by katquatermass** [comment]
Fair point. Do we use Slack for holding links for anything else? Pinned
link sounds pretty good.

**Comment by katquatermass** [comment]
We have not yet set a rota. I think there is not enough appetite among staff for doing that yet, so we should see what can be achieved by adhoc participation for the next 3 months and then look at our stats and decide.
