### ISSUE TITLE
Funder logos in hexagons

### ISSUE THREAD

**Issue by katjam** [neontribe/www#72]
**What needs doing?**
Discussed at 7 May catchup #54 

Will put logos in hexagons (some concerns about the legal implications on 'logo' design) 

Agreed that since they will all be framed the same it should be obvious is not part of logo design. If it causes issue with funders - we can think again/ change the design.

We think more hexagons improves our overall site design

**Plan**
- [x] Put hexagon frames around the logos on How we work page

**Comment by HedgehogHolly** [comment]
@katjam can I close this now?

**Comment by katjam** [comment]
@HedgehogHolly yep - if your code was on the master branch - it would have closed itself.
