### ISSUE TITLE
Catch up meeting 21st May

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#82]
https://meet.google.com/pbx-tztm-egm

**Agenda**
- [x] Review actions from #76 
- [x] Discuss any outstanding PRs
- [x] Make sure issues and milestones are still current
- [x] Discuss progress on MVP design - issues #71 #75 #81 
- [x] Discuss wether project names should be descriptive rather than the name of the client

**Notes From Meeting**
- Agreed on a hard deadline for release of MVP **28th June 2019**
- Agreed on new designs #71 #75 but more emphasis on the fact the accordion is clickable needs looking at
- Discusses wether project names should be descriptive and we decided with the new design that it is not necessary as the description is already underneath
- Next meeting will be in 3 weeks time on the **11th June 2019** as its only copy and coding that needs to be done, not much to discuss as this point _(that may change)_
- @HedgehogHolly to code the new design for How We Work page

**Next Actions for 11th June**
- [x] @HedgehogHolly to code the new design for How We Work page
- [x] @HedgehogHolly create pull request for The Tribe pages new design
- [x] @HedgehogHolly to update copy issues to reflect new design
- [ ] @harryharrold, @roseb04 and @katquatermass to work on copy
- [x] @alexalala to deal with Ollie's PR

**Comment by HedgehogHolly** [comment]
attendance: @HedgehogHolly @falconx @roseb04 @alexalala @amandaneontribe

**Comment by katquatermass** [comment]
@roseb04 will put a meeting in to calendar for Thursday to divide up copy tasks? @harryharrold may also want in on this task.
I think we need to add entries for NCVO (I think we can do a clever one that covers Front Controller and DIagnostic Tools); for Open Data Studios (If we put the client in as them - we can talk about both IATI and Grantnav in the same post) ; for UKCF (so we can talk about digital strategy) and for Addaction  as well as the current list.
