### ISSUE TITLE
Joining the tribe survey/form

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/www#92]
**What needs doing?**
A survey or form needs to be made for people to apply or show their interest in joining Neontribe

Some research/ideas are on #47 

**Plan**
- [x] Decide how form will be built
- [x] Embed or link it to website

**Comment by roseb04** [comment]
We need to think about:
- What data we are collecting from people and why?
- Who checks to see whether anyone has filled out the form? (for instance, you have to log in to typeform and look at the results.)
- Who controls/manages the data? (deleting when necessary) 
- What level of "risk" are we able to sit with for GDPR?
- Privacy policy and making it clear how people can delete their data

**Comment by roseb04** [comment]
@harryharrold has confirmed we will be using Google Forms as it is approved by our privacy impact assessment

**Comment by HedgehogHolly** [comment]
@harryharrold 

https://docs.google.com/forms/d/1fhw9HImodvkwJr-drRhWBBeD8uW-O5sDP8S5SpPRQIA/edit?usp=sharing
